wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 6
max_features:
  value: 16
min_samples_leaf:
  value: 692
min_samples_split:
  value: 13
splitter:
  value: random
