wandb_version: 1

_callback:
  desc: null
  value: wandb.sdk.wandb_run.Run._config_callback
_items:
  desc: null
  value:
    _callback: wandb.sdk.wandb_run.Run._config_callback
    _items:
      _callback: wandb.sdk.wandb_run.Run._config_callback
      _items:
        _callback: wandb.sdk.wandb_run.Run._config_callback
        _items:
          _callback: wandb.sdk.wandb_run.Run._config_callback
          _items:
            _callback: wandb.sdk.wandb_run.Run._config_callback
            _items:
              _callback: wandb.sdk.wandb_run.Run._config_callback
              _items:
                _callback: wandb.sdk.wandb_run.Run._config_callback
                _items:
                  _callback: wandb.sdk.wandb_run.Run._config_callback
                  _items:
                    _callback: wandb.sdk.wandb_run.Run._config_callback
                    _items:
                      _callback: wandb.sdk.wandb_run.Run._config_callback
                      _items:
                        _callback: wandb.sdk.wandb_run.Run._config_callback
                        _items:
                          _callback: wandb.sdk.wandb_run.Run._config_callback
                          _items:
                            _callback: wandb.sdk.wandb_run.Run._config_callback
                            _items:
                              _callback: wandb.sdk.wandb_run.Run._config_callback
                              _items:
                                _callback: wandb.sdk.wandb_run.Run._config_callback
                                _items:
                                  _callback: wandb.sdk.wandb_run.Run._config_callback
                                  _items:
                                    _callback: wandb.sdk.wandb_run.Run._config_callback
                                    _items:
                                      _wandb:
                                        cli_version: 0.10.12
                                        framework: sklearn
                                        is_jupyter_run: false
                                        is_kaggle_kernel: false
                                        python_version: 3.9.1
                                      class_weight: balanced
                                      criterion: gini
                                      max_depth: 4
                                      max_features: 15
                                      min_samples_leaf: 429
                                      min_samples_split: 311
                                      splitter: random
                                    _locked: {}
                                    _settings: <wandb.sdk.wandb_settings.Settings
                                      object at 0x00000227E9CDF430>
                                    _users: {}
                                    _users_cnt: 0
                                    _users_inv: {}
                                    _wandb:
                                      cli_version: 0.10.12
                                      framework: sklearn
                                      is_jupyter_run: false
                                      is_kaggle_kernel: false
                                      python_version: 3.9.1
                                    class_weight: balanced
                                    criterion: gini
                                    max_depth: 9
                                    max_features: 20
                                    min_samples_leaf: 520
                                    min_samples_split: 822
                                    splitter: best
                                  _locked: {}
                                  _settings: <wandb.sdk.wandb_settings.Settings object
                                    at 0x00000227EA38F310>
                                  _users: {}
                                  _users_cnt: 0
                                  _users_inv: {}
                                  _wandb:
                                    cli_version: 0.10.12
                                    framework: sklearn
                                    is_jupyter_run: false
                                    is_kaggle_kernel: false
                                    python_version: 3.9.1
                                  class_weight: balanced
                                  criterion: gini
                                  max_depth: 6
                                  max_features: 26
                                  min_samples_leaf: 470
                                  min_samples_split: 828
                                  splitter: best
                                _locked: {}
                                _settings: <wandb.sdk.wandb_settings.Settings object
                                  at 0x00000227EA3967F0>
                                _users: {}
                                _users_cnt: 0
                                _users_inv: {}
                                _wandb:
                                  cli_version: 0.10.12
                                  framework: sklearn
                                  is_jupyter_run: false
                                  is_kaggle_kernel: false
                                  python_version: 3.9.1
                                class_weight: balanced
                                criterion: gini
                                max_depth: 9
                                max_features: 28
                                min_samples_leaf: 428
                                min_samples_split: 759
                                splitter: best
                              _locked: {}
                              _settings: <wandb.sdk.wandb_settings.Settings object
                                at 0x00000227EA3D9040>
                              _users: {}
                              _users_cnt: 0
                              _users_inv: {}
                              _wandb:
                                cli_version: 0.10.12
                                framework: sklearn
                                is_jupyter_run: false
                                is_kaggle_kernel: false
                                python_version: 3.9.1
                              class_weight: balanced
                              criterion: entropy
                              max_depth: 10
                              max_features: 15
                              min_samples_leaf: 405
                              min_samples_split: 731
                              splitter: random
                            _locked: {}
                            _settings: <wandb.sdk.wandb_settings.Settings object at
                              0x00000227EA3D9DF0>
                            _users: {}
                            _users_cnt: 0
                            _users_inv: {}
                            _wandb:
                              cli_version: 0.10.12
                              framework: sklearn
                              is_jupyter_run: false
                              is_kaggle_kernel: false
                              python_version: 3.9.1
                            class_weight: balanced
                            criterion: entropy
                            max_depth: 9
                            max_features: 13
                            min_samples_leaf: 401
                            min_samples_split: 943
                            splitter: random
                          _locked: {}
                          _settings: <wandb.sdk.wandb_settings.Settings object at
                            0x00000227EA3D91F0>
                          _users: {}
                          _users_cnt: 0
                          _users_inv: {}
                          _wandb:
                            cli_version: 0.10.12
                            framework: sklearn
                            is_jupyter_run: false
                            is_kaggle_kernel: false
                            python_version: 3.9.1
                          class_weight: balanced
                          criterion: gini
                          max_depth: 7
                          max_features: 20
                          min_samples_leaf: 829
                          min_samples_split: 157
                          splitter: random
                        _locked: {}
                        _settings: <wandb.sdk.wandb_settings.Settings object at 0x00000227EAB8FFD0>
                        _users: {}
                        _users_cnt: 0
                        _users_inv: {}
                        _wandb:
                          cli_version: 0.10.12
                          framework: sklearn
                          is_jupyter_run: false
                          is_kaggle_kernel: false
                          python_version: 3.9.1
                        class_weight: balanced
                        criterion: entropy
                        max_depth: 10
                        max_features: 30
                        min_samples_leaf: 982
                        min_samples_split: 825
                        splitter: random
                      _locked: {}
                      _settings: <wandb.sdk.wandb_settings.Settings object at 0x00000227EAB8F4C0>
                      _users: {}
                      _users_cnt: 0
                      _users_inv: {}
                      _wandb:
                        cli_version: 0.10.12
                        framework: sklearn
                        is_jupyter_run: false
                        is_kaggle_kernel: false
                        python_version: 3.9.1
                      class_weight: balanced
                      criterion: entropy
                      max_depth: 3
                      max_features: 25
                      min_samples_leaf: 862
                      min_samples_split: 234
                      splitter: random
                    _locked: {}
                    _settings: <wandb.sdk.wandb_settings.Settings object at 0x00000227EABBA880>
                    _users: {}
                    _users_cnt: 0
                    _users_inv: {}
                    _wandb:
                      cli_version: 0.10.12
                      framework: sklearn
                      is_jupyter_run: false
                      is_kaggle_kernel: false
                      python_version: 3.9.1
                    class_weight: balanced
                    criterion: entropy
                    max_depth: 8
                    max_features: 28
                    min_samples_leaf: 141
                    min_samples_split: 680
                    splitter: random
                  _locked: {}
                  _settings: <wandb.sdk.wandb_settings.Settings object at 0x00000227EA4052B0>
                  _users: {}
                  _users_cnt: 0
                  _users_inv: {}
                  _wandb:
                    cli_version: 0.10.12
                    framework: sklearn
                    is_jupyter_run: false
                    is_kaggle_kernel: false
                    python_version: 3.9.1
                  class_weight: balanced
                  criterion: entropy
                  max_depth: 5
                  max_features: 18
                  min_samples_leaf: 998
                  min_samples_split: 109
                  splitter: random
                _locked: {}
                _settings: <wandb.sdk.wandb_settings.Settings object at 0x00000227EA425DC0>
                _users: {}
                _users_cnt: 0
                _users_inv: {}
                _wandb:
                  cli_version: 0.10.12
                  framework: sklearn
                  is_jupyter_run: false
                  is_kaggle_kernel: false
                  python_version: 3.9.1
                class_weight: balanced
                criterion: gini
                max_depth: 3
                max_features: 38
                min_samples_leaf: 823
                min_samples_split: 670
                splitter: best
              _locked: {}
              _settings: <wandb.sdk.wandb_settings.Settings object at 0x00000227EA42F340>
              _users: {}
              _users_cnt: 0
              _users_inv: {}
              _wandb:
                cli_version: 0.10.12
                framework: sklearn
                is_jupyter_run: false
                is_kaggle_kernel: false
                python_version: 3.9.1
              class_weight: balanced
              criterion: entropy
              max_depth: 4
              max_features: 4
              min_samples_leaf: 554
              min_samples_split: 4
              splitter: random
            _locked: {}
            _settings: <wandb.sdk.wandb_settings.Settings object at 0x00000227EA3D9B50>
            _users: {}
            _users_cnt: 0
            _users_inv: {}
            _wandb:
              cli_version: 0.10.12
              framework: sklearn
              is_jupyter_run: false
              is_kaggle_kernel: false
              python_version: 3.9.1
            class_weight: balanced
            criterion: gini
            max_depth: 6
            max_features: 36
            min_samples_leaf: 32
            min_samples_split: 188
            splitter: best
          _locked: {}
          _settings: <wandb.sdk.wandb_settings.Settings object at 0x00000227EA425FD0>
          _users: {}
          _users_cnt: 0
          _users_inv: {}
          _wandb:
            cli_version: 0.10.12
            framework: sklearn
            is_jupyter_run: false
            is_kaggle_kernel: false
            python_version: 3.9.1
          class_weight: balanced
          criterion: gini
          max_depth: 6
          max_features: 10
          min_samples_leaf: 302
          min_samples_split: 458
          splitter: random
        _locked: {}
        _settings: <wandb.sdk.wandb_settings.Settings object at 0x00000227EA46BC40>
        _users: {}
        _users_cnt: 0
        _users_inv: {}
        _wandb:
          cli_version: 0.10.12
          framework: sklearn
          is_jupyter_run: false
          is_kaggle_kernel: false
          python_version: 3.9.1
        class_weight: balanced
        criterion: gini
        max_depth: 8
        max_features: 16
        min_samples_leaf: 123
        min_samples_split: 912
        splitter: random
      _locked: {}
      _settings: <wandb.sdk.wandb_settings.Settings object at 0x00000227EA45FFA0>
      _users: {}
      _users_cnt: 0
      _users_inv: {}
      _wandb:
        cli_version: 0.10.12
        framework: sklearn
        is_jupyter_run: false
        is_kaggle_kernel: false
        python_version: 3.9.1
      class_weight: balanced
      criterion: entropy
      max_depth: 4
      max_features: 21
      min_samples_leaf: 631
      min_samples_split: 103
      splitter: random
    _locked: {}
    _settings: <wandb.sdk.wandb_settings.Settings object at 0x00000227EA645940>
    _users: {}
    _users_cnt: 0
    _users_inv: {}
    _wandb:
      cli_version: 0.10.12
      framework: sklearn
      is_jupyter_run: false
      is_kaggle_kernel: false
      python_version: 3.9.1
    class_weight: balanced
    criterion: gini
    max_depth: 10
    max_features: 17
    min_samples_leaf: 454
    min_samples_split: 887
    splitter: best
_locked:
  desc: null
  value: {}
_settings:
  desc: null
  value: <wandb.sdk.wandb_settings.Settings object at 0x00000227EA65E190>
_users:
  desc: null
  value: {}
_users_cnt:
  desc: null
  value: 0
_users_inv:
  desc: null
  value: {}
_wandb:
  desc: null
  value:
    cli_version: 0.10.12
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.1
class_weight:
  desc: null
  value: balanced
criterion:
  desc: null
  value: entropy
max_depth:
  desc: null
  value: 9
max_features:
  desc: null
  value: 28
min_samples_leaf:
  desc: null
  value: 894
min_samples_split:
  desc: null
  value: 180
splitter:
  desc: null
  value: random
