wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: entropy
max_depth:
  value: 9
max_features:
  value: 22
min_samples_leaf:
  value: 955
min_samples_split:
  value: 666
splitter:
  value: best
