wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 9
max_features:
  value: 38
min_samples_leaf:
  value: 448
min_samples_split:
  value: 919
splitter:
  value: best
