wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: entropy
max_depth:
  value: 8
max_features:
  value: 28
min_samples_leaf:
  value: 398
min_samples_split:
  value: 928
splitter:
  value: random
