wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: entropy
max_depth:
  value: 7
max_features:
  value: 39
min_samples_leaf:
  value: 78
min_samples_split:
  value: 368
splitter:
  value: best
