wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: entropy
max_depth:
  value: 6
max_features:
  value: 13
min_samples_leaf:
  value: 52
min_samples_split:
  value: 478
splitter:
  value: best
