wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: entropy
max_depth:
  value: 7
max_features:
  value: 31
min_samples_leaf:
  value: 776
min_samples_split:
  value: 465
splitter:
  value: random
