wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 8
max_features:
  value: 18
min_samples_leaf:
  value: 453
min_samples_split:
  value: 887
splitter:
  value: best
