wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 10
max_features:
  value: 10
min_samples_leaf:
  value: 956
min_samples_split:
  value: 644
splitter:
  value: best
