wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: entropy
max_depth:
  value: 9
max_features:
  value: 23
min_samples_leaf:
  value: 168
min_samples_split:
  value: 127
splitter:
  value: random
