wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 7
max_features:
  value: 2
min_samples_leaf:
  value: 533
min_samples_split:
  value: 918
splitter:
  value: random
