wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 8
max_features:
  value: 27
min_samples_leaf:
  value: 20
min_samples_split:
  value: 355
splitter:
  value: best
