wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: entropy
max_depth:
  value: 10
max_features:
  value: 25
min_samples_leaf:
  value: 322
min_samples_split:
  value: 364
splitter:
  value: random
