wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 5
max_features:
  value: 18
min_samples_leaf:
  value: 93
min_samples_split:
  value: 664
splitter:
  value: best
