wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: entropy
max_depth:
  value: 7
max_features:
  value: 3
min_samples_leaf:
  value: 290
min_samples_split:
  value: 803
splitter:
  value: best
