wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: entropy
max_depth:
  value: 8
max_features:
  value: 12
min_samples_leaf:
  value: 758
min_samples_split:
  value: 293
splitter:
  value: best
