wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 10
max_features:
  value: 37
min_samples_leaf:
  value: 35
min_samples_split:
  value: 354
splitter:
  value: random
