wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: entropy
max_depth:
  value: 7
max_features:
  value: 13
min_samples_leaf:
  value: 534
min_samples_split:
  value: 968
splitter:
  value: best
