wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: entropy
max_depth:
  value: 5
max_features:
  value: 2
min_samples_leaf:
  value: 744
min_samples_split:
  value: 741
splitter:
  value: random
