wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 7
max_features:
  value: 14
min_samples_leaf:
  value: 753
min_samples_split:
  value: 552
splitter:
  value: best
