wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: entropy
max_depth:
  value: 3
max_features:
  value: 16
min_samples_leaf:
  value: 74
min_samples_split:
  value: 634
splitter:
  value: best
