wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 5
max_features:
  value: 26
min_samples_leaf:
  value: 181
min_samples_split:
  value: 303
splitter:
  value: random
