wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 10
max_features:
  value: 9
min_samples_leaf:
  value: 23
min_samples_split:
  value: 309
splitter:
  value: best
