wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 3
max_features:
  value: 17
min_samples_leaf:
  value: 119
min_samples_split:
  value: 203
splitter:
  value: random
