wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 6
max_features:
  value: 18
min_samples_leaf:
  value: 582
min_samples_split:
  value: 66
splitter:
  value: best
