wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 6
max_features:
  value: 15
min_samples_leaf:
  value: 786
min_samples_split:
  value: 907
splitter:
  value: random
