wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 7
max_features:
  value: 34
min_samples_leaf:
  value: 247
min_samples_split:
  value: 612
splitter:
  value: best
