wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 4
max_features:
  value: 9
min_samples_leaf:
  value: 458
min_samples_split:
  value: 474
splitter:
  value: random
