wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: entropy
max_depth:
  value: 9
max_features:
  value: 13
min_samples_leaf:
  value: 517
min_samples_split:
  value: 165
splitter:
  value: random
