wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 9
max_features:
  value: 23
min_samples_leaf:
  value: 242
min_samples_split:
  value: 734
splitter:
  value: best
