wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 7
max_features:
  value: 3
min_samples_leaf:
  value: 511
min_samples_split:
  value: 917
splitter:
  value: best
