wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 3
max_features:
  value: 1
min_samples_leaf:
  value: 644
min_samples_split:
  value: 950
splitter:
  value: best
