wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 4
max_features:
  value: 40
min_samples_leaf:
  value: 58
min_samples_split:
  value: 57
splitter:
  value: random
