wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 5
max_features:
  value: 11
min_samples_leaf:
  value: 166
min_samples_split:
  value: 197
splitter:
  value: best
