wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 8
max_features:
  value: 16
min_samples_leaf:
  value: 807
min_samples_split:
  value: 676
splitter:
  value: random
