wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: entropy
max_depth:
  value: 9
max_features:
  value: 39
min_samples_leaf:
  value: 736
min_samples_split:
  value: 665
splitter:
  value: random
