wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: entropy
max_depth:
  value: 7
max_features:
  value: 36
min_samples_leaf:
  value: 976
min_samples_split:
  value: 258
splitter:
  value: random
