wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: entropy
max_depth:
  value: 7
max_features:
  value: 10
min_samples_leaf:
  value: 405
min_samples_split:
  value: 260
splitter:
  value: best
