wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: entropy
max_depth:
  value: 9
max_features:
  value: 24
min_samples_leaf:
  value: 980
min_samples_split:
  value: 666
splitter:
  value: best
