wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 5
max_features:
  value: 25
min_samples_leaf:
  value: 591
min_samples_split:
  value: 156
splitter:
  value: random
