wandb_version: 1

_callback:
  desc: null
  value: wandb.sdk.wandb_run.Run._config_callback
_items:
  desc: null
  value:
    _callback: wandb.sdk.wandb_run.Run._config_callback
    _items:
      _callback: wandb.sdk.wandb_run.Run._config_callback
      _items:
        _callback: wandb.sdk.wandb_run.Run._config_callback
        _items:
          _callback: wandb.sdk.wandb_run.Run._config_callback
          _items:
            _callback: wandb.sdk.wandb_run.Run._config_callback
            _items:
              _callback: wandb.sdk.wandb_run.Run._config_callback
              _items:
                _callback: wandb.sdk.wandb_run.Run._config_callback
                _items:
                  _callback: wandb.sdk.wandb_run.Run._config_callback
                  _items:
                    _wandb:
                      cli_version: 0.10.12
                      framework: sklearn
                      is_jupyter_run: false
                      is_kaggle_kernel: false
                      python_version: 3.9.1
                    class_weight: balanced
                    criterion: entropy
                    max_depth: 5
                    max_features: 13
                    min_samples_leaf: 662
                    min_samples_split: 937
                    splitter: best
                  _locked: {}
                  _settings: <wandb.sdk.wandb_settings.Settings object at 0x000001CFA754C430>
                  _users: {}
                  _users_cnt: 0
                  _users_inv: {}
                  _wandb:
                    cli_version: 0.10.12
                    framework: sklearn
                    is_jupyter_run: false
                    is_kaggle_kernel: false
                    python_version: 3.9.1
                  class_weight: balanced
                  criterion: gini
                  max_depth: 3
                  max_features: 16
                  min_samples_leaf: 725
                  min_samples_split: 56
                  splitter: best
                _locked: {}
                _settings: <wandb.sdk.wandb_settings.Settings object at 0x000001CFA7653730>
                _users: {}
                _users_cnt: 0
                _users_inv: {}
                _wandb:
                  cli_version: 0.10.12
                  framework: sklearn
                  is_jupyter_run: false
                  is_kaggle_kernel: false
                  python_version: 3.9.1
                class_weight: balanced
                criterion: gini
                max_depth: 7
                max_features: 10
                min_samples_leaf: 824
                min_samples_split: 880
                splitter: best
              _locked: {}
              _settings: <wandb.sdk.wandb_settings.Settings object at 0x000001CFA76927C0>
              _users: {}
              _users_cnt: 0
              _users_inv: {}
              _wandb:
                cli_version: 0.10.12
                framework: sklearn
                is_jupyter_run: false
                is_kaggle_kernel: false
                python_version: 3.9.1
              class_weight: balanced
              criterion: gini
              max_depth: 4
              max_features: 30
              min_samples_leaf: 629
              min_samples_split: 536
              splitter: best
            _locked: {}
            _settings: <wandb.sdk.wandb_settings.Settings object at 0x000001CFA76A3BB0>
            _users: {}
            _users_cnt: 0
            _users_inv: {}
            _wandb:
              cli_version: 0.10.12
              framework: sklearn
              is_jupyter_run: false
              is_kaggle_kernel: false
              python_version: 3.9.1
            class_weight: balanced
            criterion: gini
            max_depth: 3
            max_features: 20
            min_samples_leaf: 576
            min_samples_split: 586
            splitter: best
          _locked: {}
          _settings: <wandb.sdk.wandb_settings.Settings object at 0x000001CFA767B8E0>
          _users: {}
          _users_cnt: 0
          _users_inv: {}
          _wandb:
            cli_version: 0.10.12
            framework: sklearn
            is_jupyter_run: false
            is_kaggle_kernel: false
            python_version: 3.9.1
          class_weight: balanced
          criterion: entropy
          max_depth: 3
          max_features: 39
          min_samples_leaf: 628
          min_samples_split: 654
          splitter: best
        _locked: {}
        _settings: <wandb.sdk.wandb_settings.Settings object at 0x000001CFA76D2130>
        _users: {}
        _users_cnt: 0
        _users_inv: {}
        _wandb:
          cli_version: 0.10.12
          framework: sklearn
          is_jupyter_run: false
          is_kaggle_kernel: false
          python_version: 3.9.1
        class_weight: balanced
        criterion: entropy
        max_depth: 4
        max_features: 40
        min_samples_leaf: 521
        min_samples_split: 578
        splitter: best
      _locked: {}
      _settings: <wandb.sdk.wandb_settings.Settings object at 0x000001CFA76E0370>
      _users: {}
      _users_cnt: 0
      _users_inv: {}
      _wandb:
        cli_version: 0.10.12
        framework: sklearn
        is_jupyter_run: false
        is_kaggle_kernel: false
        python_version: 3.9.1
      class_weight: balanced
      criterion: gini
      max_depth: 3
      max_features: 40
      min_samples_leaf: 777
      min_samples_split: 348
      splitter: best
    _locked: {}
    _settings: <wandb.sdk.wandb_settings.Settings object at 0x000001CFA76F6A00>
    _users: {}
    _users_cnt: 0
    _users_inv: {}
    _wandb:
      cli_version: 0.10.12
      framework: sklearn
      is_jupyter_run: false
      is_kaggle_kernel: false
      python_version: 3.9.1
    class_weight: balanced
    criterion: entropy
    max_depth: 6
    max_features: 40
    min_samples_leaf: 27
    min_samples_split: 719
    splitter: best
_locked:
  desc: null
  value: {}
_settings:
  desc: null
  value: <wandb.sdk.wandb_settings.Settings object at 0x000001CFA77062B0>
_users:
  desc: null
  value: {}
_users_cnt:
  desc: null
  value: 0
_users_inv:
  desc: null
  value: {}
_wandb:
  desc: null
  value:
    cli_version: 0.10.12
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.1
class_weight:
  desc: null
  value: balanced
criterion:
  desc: null
  value: entropy
max_depth:
  desc: null
  value: 7
max_features:
  desc: null
  value: 40
min_samples_leaf:
  desc: null
  value: 9
min_samples_split:
  desc: null
  value: 652
splitter:
  desc: null
  value: best
