wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 6
max_features:
  value: 10
min_samples_leaf:
  value: 302
min_samples_split:
  value: 458
splitter:
  value: random
