wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: entropy
max_depth:
  value: 3
max_features:
  value: 23
min_samples_leaf:
  value: 858
min_samples_split:
  value: 186
splitter:
  value: random
