wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: entropy
max_depth:
  value: 4
max_features:
  value: 24
min_samples_leaf:
  value: 856
min_samples_split:
  value: 203
splitter:
  value: random
