wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 6
max_features:
  value: 7
min_samples_leaf:
  value: 416
min_samples_split:
  value: 675
splitter:
  value: best
