wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 4
max_features:
  value: 2
min_samples_leaf:
  value: 526
min_samples_split:
  value: 432
splitter:
  value: random
