wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: entropy
max_depth:
  value: 5
max_features:
  value: 22
min_samples_leaf:
  value: 539
min_samples_split:
  value: 614
splitter:
  value: best
