wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: entropy
max_depth:
  value: 4
max_features:
  value: 16
min_samples_leaf:
  value: 833
min_samples_split:
  value: 239
splitter:
  value: random
