wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 10
max_features:
  value: 1
min_samples_leaf:
  value: 569
min_samples_split:
  value: 859
splitter:
  value: random
