wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 7
max_features:
  value: 23
min_samples_leaf:
  value: 159
min_samples_split:
  value: 37
splitter:
  value: best
