wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: entropy
max_depth:
  value: 7
max_features:
  value: 18
min_samples_leaf:
  value: 79
min_samples_split:
  value: 345
splitter:
  value: random
