wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: entropy
max_depth:
  value: 3
max_features:
  value: 25
min_samples_leaf:
  value: 862
min_samples_split:
  value: 234
splitter:
  value: random
