wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: entropy
max_depth:
  value: 8
max_features:
  value: 3
min_samples_leaf:
  value: 579
min_samples_split:
  value: 174
splitter:
  value: random
