wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: entropy
max_depth:
  value: 3
max_features:
  value: 30
min_samples_leaf:
  value: 922
min_samples_split:
  value: 40
splitter:
  value: random
