wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: entropy
max_depth:
  value: 9
max_features:
  value: 26
min_samples_leaf:
  value: 529
min_samples_split:
  value: 845
splitter:
  value: best
