wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: entropy
max_depth:
  value: 4
max_features:
  value: 21
min_samples_leaf:
  value: 631
min_samples_split:
  value: 103
splitter:
  value: random
