wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 4
max_features:
  value: 15
min_samples_leaf:
  value: 429
min_samples_split:
  value: 311
splitter:
  value: random
