wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 6
max_features:
  value: 36
min_samples_leaf:
  value: 32
min_samples_split:
  value: 188
splitter:
  value: best
