wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: entropy
max_depth:
  value: 9
max_features:
  value: 39
min_samples_leaf:
  value: 136
min_samples_split:
  value: 834
splitter:
  value: best
