wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 6
max_features:
  value: 21
min_samples_leaf:
  value: 60
min_samples_split:
  value: 710
splitter:
  value: best
