wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 6
max_features:
  value: 24
min_samples_leaf:
  value: 957
min_samples_split:
  value: 71
splitter:
  value: random
