wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 3
max_features:
  value: 39
min_samples_leaf:
  value: 330
min_samples_split:
  value: 621
splitter:
  value: random
