wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 10
max_features:
  value: 26
min_samples_leaf:
  value: 753
min_samples_split:
  value: 672
splitter:
  value: random
