wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 10
max_features:
  value: 18
min_samples_leaf:
  value: 218
min_samples_split:
  value: 426
splitter:
  value: best
