wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 9
max_features:
  value: 21
min_samples_leaf:
  value: 730
min_samples_split:
  value: 726
splitter:
  value: best
