wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: entropy
max_depth:
  value: 3
max_features:
  value: 40
min_samples_leaf:
  value: 794
min_samples_split:
  value: 350
splitter:
  value: random
