wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: entropy
max_depth:
  value: 6
max_features:
  value: 33
min_samples_leaf:
  value: 448
min_samples_split:
  value: 735
splitter:
  value: random
