wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 9
max_features:
  value: 16
min_samples_leaf:
  value: 858
min_samples_split:
  value: 60
splitter:
  value: random
