wandb_version: 1

_callback:
  desc: null
  value: wandb.sdk.wandb_run.Run._config_callback
_items:
  desc: null
  value:
    _callback: wandb.sdk.wandb_run.Run._config_callback
    _items:
      _callback: wandb.sdk.wandb_run.Run._config_callback
      _items:
        _callback: wandb.sdk.wandb_run.Run._config_callback
        _items:
          _callback: wandb.sdk.wandb_run.Run._config_callback
          _items:
            _callback: wandb.sdk.wandb_run.Run._config_callback
            _items:
              _callback: wandb.sdk.wandb_run.Run._config_callback
              _items:
                _callback: wandb.sdk.wandb_run.Run._config_callback
                _items:
                  _callback: wandb.sdk.wandb_run.Run._config_callback
                  _items:
                    _wandb:
                      cli_version: 0.10.12
                      framework: sklearn
                      is_jupyter_run: false
                      is_kaggle_kernel: false
                      python_version: 3.9.1
                    class_weight: balanced
                    criterion: gini
                    max_depth: 3
                    max_features: 26
                    min_samples_leaf: 487
                    min_samples_split: 824
                    splitter: random
                  _locked: {}
                  _settings: <wandb.sdk.wandb_settings.Settings object at 0x0000017E567CC430>
                  _users: {}
                  _users_cnt: 0
                  _users_inv: {}
                  _wandb:
                    cli_version: 0.10.12
                    framework: sklearn
                    is_jupyter_run: false
                    is_kaggle_kernel: false
                    python_version: 3.9.1
                  class_weight: balanced
                  criterion: gini
                  max_depth: 7
                  max_features: 29
                  min_samples_leaf: 565
                  min_samples_split: 707
                  splitter: random
                _locked: {}
                _settings: <wandb.sdk.wandb_settings.Settings object at 0x0000017E568DA760>
                _users: {}
                _users_cnt: 0
                _users_inv: {}
                _wandb:
                  cli_version: 0.10.12
                  framework: sklearn
                  is_jupyter_run: false
                  is_kaggle_kernel: false
                  python_version: 3.9.1
                class_weight: balanced
                criterion: entropy
                max_depth: 3
                max_features: 3
                min_samples_leaf: 321
                min_samples_split: 136
                splitter: best
              _locked: {}
              _settings: <wandb.sdk.wandb_settings.Settings object at 0x0000017E568FBDF0>
              _users: {}
              _users_cnt: 0
              _users_inv: {}
              _wandb:
                cli_version: 0.10.12
                framework: sklearn
                is_jupyter_run: false
                is_kaggle_kernel: false
                python_version: 3.9.1
              class_weight: balanced
              criterion: gini
              max_depth: 9
              max_features: 39
              min_samples_leaf: 476
              min_samples_split: 783
              splitter: random
            _locked: {}
            _settings: <wandb.sdk.wandb_settings.Settings object at 0x0000017E56914850>
            _users: {}
            _users_cnt: 0
            _users_inv: {}
            _wandb:
              cli_version: 0.10.12
              framework: sklearn
              is_jupyter_run: false
              is_kaggle_kernel: false
              python_version: 3.9.1
            class_weight: balanced
            criterion: entropy
            max_depth: 3
            max_features: 35
            min_samples_leaf: 719
            min_samples_split: 115
            splitter: best
          _locked: {}
          _settings: <wandb.sdk.wandb_settings.Settings object at 0x0000017E5693CB50>
          _users: {}
          _users_cnt: 0
          _users_inv: {}
          _wandb:
            cli_version: 0.10.12
            framework: sklearn
            is_jupyter_run: false
            is_kaggle_kernel: false
            python_version: 3.9.1
          class_weight: balanced
          criterion: entropy
          max_depth: 5
          max_features: 19
          min_samples_leaf: 611
          min_samples_split: 839
          splitter: random
        _locked: {}
        _settings: <wandb.sdk.wandb_settings.Settings object at 0x0000017E569484F0>
        _users: {}
        _users_cnt: 0
        _users_inv: {}
        _wandb:
          cli_version: 0.10.12
          framework: sklearn
          is_jupyter_run: false
          is_kaggle_kernel: false
          python_version: 3.9.1
        class_weight: balanced
        criterion: entropy
        max_depth: 3
        max_features: 4
        min_samples_leaf: 740
        min_samples_split: 548
        splitter: random
      _locked: {}
      _settings: <wandb.sdk.wandb_settings.Settings object at 0x0000017E57852C10>
      _users: {}
      _users_cnt: 0
      _users_inv: {}
      _wandb:
        cli_version: 0.10.12
        framework: sklearn
        is_jupyter_run: false
        is_kaggle_kernel: false
        python_version: 3.9.1
      class_weight: balanced
      criterion: gini
      max_depth: 3
      max_features: 22
      min_samples_leaf: 543
      min_samples_split: 587
      splitter: random
    _locked: {}
    _settings: <wandb.sdk.wandb_settings.Settings object at 0x0000017E578581F0>
    _users: {}
    _users_cnt: 0
    _users_inv: {}
    _wandb:
      cli_version: 0.10.12
      framework: sklearn
      is_jupyter_run: false
      is_kaggle_kernel: false
      python_version: 3.9.1
    class_weight: balanced
    criterion: entropy
    max_depth: 3
    max_features: 33
    min_samples_leaf: 519
    min_samples_split: 142
    splitter: random
_locked:
  desc: null
  value: {}
_settings:
  desc: null
  value: <wandb.sdk.wandb_settings.Settings object at 0x0000017E5788BFA0>
_users:
  desc: null
  value: {}
_users_cnt:
  desc: null
  value: 0
_users_inv:
  desc: null
  value: {}
_wandb:
  desc: null
  value:
    cli_version: 0.10.12
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.1
class_weight:
  desc: null
  value: balanced
criterion:
  desc: null
  value: entropy
max_depth:
  desc: null
  value: 6
max_features:
  desc: null
  value: 33
min_samples_leaf:
  desc: null
  value: 858
min_samples_split:
  desc: null
  value: 96
splitter:
  desc: null
  value: best
