wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 4
max_features:
  value: 23
min_samples_leaf:
  value: 53
min_samples_split:
  value: 16
splitter:
  value: best
