wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: entropy
max_depth:
  value: 8
max_features:
  value: 24
min_samples_leaf:
  value: 157
min_samples_split:
  value: 57
splitter:
  value: best
