wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 9
max_features:
  value: 25
min_samples_leaf:
  value: 933
min_samples_split:
  value: 993
splitter:
  value: random
