wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 4
max_features:
  value: 16
min_samples_leaf:
  value: 31
min_samples_split:
  value: 276
splitter:
  value: best
