wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 9
max_features:
  value: 18
min_samples_leaf:
  value: 961
min_samples_split:
  value: 976
splitter:
  value: best
