wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 4
max_features:
  value: 22
min_samples_leaf:
  value: 815
min_samples_split:
  value: 631
splitter:
  value: best
