wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 10
max_features:
  value: 12
min_samples_leaf:
  value: 888
min_samples_split:
  value: 258
splitter:
  value: best
