wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 9
max_features:
  value: 8
min_samples_leaf:
  value: 8
min_samples_split:
  value: 762
splitter:
  value: best
