wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: entropy
max_depth:
  value: 3
max_features:
  value: 39
min_samples_leaf:
  value: 881
min_samples_split:
  value: 52
splitter:
  value: random
