wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: entropy
max_depth:
  value: 6
max_features:
  value: 26
min_samples_leaf:
  value: 468
min_samples_split:
  value: 246
splitter:
  value: best
