wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: entropy
max_depth:
  value: 6
max_features:
  value: 20
min_samples_leaf:
  value: 278
min_samples_split:
  value: 434
splitter:
  value: random
