wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 8
max_features:
  value: 3
min_samples_leaf:
  value: 440
min_samples_split:
  value: 276
splitter:
  value: random
