wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 9
max_features:
  value: 7
min_samples_leaf:
  value: 383
min_samples_split:
  value: 869
splitter:
  value: random
