wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 5
max_features:
  value: 38
min_samples_leaf:
  value: 470
min_samples_split:
  value: 834
splitter:
  value: random
