wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 10
max_features:
  value: 16
min_samples_leaf:
  value: 981
min_samples_split:
  value: 165
splitter:
  value: random
