wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: entropy
max_depth:
  value: 3
max_features:
  value: 9
min_samples_leaf:
  value: 185
min_samples_split:
  value: 320
splitter:
  value: random
