wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 4
max_features:
  value: 6
min_samples_leaf:
  value: 189
min_samples_split:
  value: 848
splitter:
  value: random
