wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 10
max_features:
  value: 5
min_samples_leaf:
  value: 185
min_samples_split:
  value: 327
splitter:
  value: best
