wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: entropy
max_depth:
  value: 4
max_features:
  value: 31
min_samples_leaf:
  value: 933
min_samples_split:
  value: 76
splitter:
  value: random
