wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: entropy
max_depth:
  value: 8
max_features:
  value: 27
min_samples_leaf:
  value: 641
min_samples_split:
  value: 711
splitter:
  value: best
