wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 7
max_features:
  value: 1
min_samples_leaf:
  value: 892
min_samples_split:
  value: 770
splitter:
  value: best
