wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 3
max_features:
  value: 11
min_samples_leaf:
  value: 275
min_samples_split:
  value: 580
splitter:
  value: random
