wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: entropy
max_depth:
  value: 4
max_features:
  value: 34
min_samples_leaf:
  value: 699
min_samples_split:
  value: 134
splitter:
  value: random
