wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: entropy
max_depth:
  value: 10
max_features:
  value: 33
min_samples_leaf:
  value: 781
min_samples_split:
  value: 1
splitter:
  value: random
