wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 4
max_features:
  value: 37
min_samples_leaf:
  value: 676
min_samples_split:
  value: 856
splitter:
  value: best
