wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 3
max_features:
  value: 36
min_samples_leaf:
  value: 448
min_samples_split:
  value: 654
splitter:
  value: random
