wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: entropy
max_depth:
  value: 4
max_features:
  value: 19
min_samples_leaf:
  value: 895
min_samples_split:
  value: 507
splitter:
  value: best
