wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: entropy
max_depth:
  value: 10
max_features:
  value: 24
min_samples_leaf:
  value: 136
min_samples_split:
  value: 577
splitter:
  value: random
