wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: entropy
max_depth:
  value: 3
max_features:
  value: 21
min_samples_leaf:
  value: 219
min_samples_split:
  value: 951
splitter:
  value: random
