wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: entropy
max_depth:
  value: 8
max_features:
  value: 32
min_samples_leaf:
  value: 969
min_samples_split:
  value: 530
splitter:
  value: random
