wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 9
max_features:
  value: 32
min_samples_leaf:
  value: 623
min_samples_split:
  value: 217
splitter:
  value: best
