wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 5
max_features:
  value: 33
min_samples_leaf:
  value: 480
min_samples_split:
  value: 265
splitter:
  value: best
