wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 8
max_features:
  value: 4
min_samples_leaf:
  value: 463
min_samples_split:
  value: 121
splitter:
  value: best
