wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 9
max_features:
  value: 27
min_samples_leaf:
  value: 160
min_samples_split:
  value: 769
splitter:
  value: random
