wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: entropy
max_depth:
  value: 9
max_features:
  value: 18
min_samples_leaf:
  value: 821
min_samples_split:
  value: 757
splitter:
  value: random
