wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 4
max_features:
  value: 16
min_samples_leaf:
  value: 555
min_samples_split:
  value: 291
splitter:
  value: random
