wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 3
max_features:
  value: 17
min_samples_leaf:
  value: 843
min_samples_split:
  value: 250
splitter:
  value: best
