wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: entropy
max_depth:
  value: 7
max_features:
  value: 26
min_samples_leaf:
  value: 702
min_samples_split:
  value: 257
splitter:
  value: random
