wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 10
max_features:
  value: 21
min_samples_leaf:
  value: 698
min_samples_split:
  value: 164
splitter:
  value: best
