wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 8
max_features:
  value: 39
min_samples_leaf:
  value: 386
min_samples_split:
  value: 742
splitter:
  value: best
