wandb_version: 1

_callback:
  desc: null
  value: wandb.sdk.wandb_run.Run._config_callback
_items:
  desc: null
  value:
    _callback: wandb.sdk.wandb_run.Run._config_callback
    _items:
      _callback: wandb.sdk.wandb_run.Run._config_callback
      _items:
        _callback: wandb.sdk.wandb_run.Run._config_callback
        _items:
          _callback: wandb.sdk.wandb_run.Run._config_callback
          _items:
            _wandb:
              cli_version: 0.10.12
              framework: sklearn
              is_jupyter_run: false
              is_kaggle_kernel: false
              python_version: 3.9.1
            class_weight: balanced
            criterion: gini
            max_depth: 10
            max_features: 38
            min_samples_leaf: 79
            min_samples_split: 364
            splitter: random
          _locked: {}
          _settings: <wandb.sdk.wandb_settings.Settings object at 0x000001ED21A2B400>
          _users: {}
          _users_cnt: 0
          _users_inv: {}
          _wandb:
            cli_version: 0.10.12
            framework: sklearn
            is_jupyter_run: false
            is_kaggle_kernel: false
            python_version: 3.9.1
          class_weight: balanced
          criterion: gini
          max_depth: 9
          max_features: 28
          min_samples_leaf: 544
          min_samples_split: 684
          splitter: random
        _locked: {}
        _settings: <wandb.sdk.wandb_settings.Settings object at 0x000001ED21B6D940>
        _users: {}
        _users_cnt: 0
        _users_inv: {}
        _wandb:
          cli_version: 0.10.12
          framework: sklearn
          is_jupyter_run: false
          is_kaggle_kernel: false
          python_version: 3.9.1
        class_weight: balanced
        criterion: gini
        max_depth: 3
        max_features: 4
        min_samples_leaf: 914
        min_samples_split: 716
        splitter: best
      _locked: {}
      _settings: <wandb.sdk.wandb_settings.Settings object at 0x000001ED21BD0D30>
      _users: {}
      _users_cnt: 0
      _users_inv: {}
      _wandb:
        cli_version: 0.10.12
        framework: sklearn
        is_jupyter_run: false
        is_kaggle_kernel: false
        python_version: 3.9.1
      class_weight: balanced
      criterion: entropy
      max_depth: 8
      max_features: 37
      min_samples_leaf: 102
      min_samples_split: 38
      splitter: random
    _locked: {}
    _settings: <wandb.sdk.wandb_settings.Settings object at 0x000001ED21B62F10>
    _users: {}
    _users_cnt: 0
    _users_inv: {}
    _wandb:
      cli_version: 0.10.12
      framework: sklearn
      is_jupyter_run: false
      is_kaggle_kernel: false
      python_version: 3.9.1
    class_weight: balanced
    criterion: gini
    max_depth: 10
    max_features: 36
    min_samples_leaf: 147
    min_samples_split: 534
    splitter: random
_locked:
  desc: null
  value: {}
_settings:
  desc: null
  value: <wandb.sdk.wandb_settings.Settings object at 0x000001ED22377910>
_users:
  desc: null
  value: {}
_users_cnt:
  desc: null
  value: 0
_users_inv:
  desc: null
  value: {}
_wandb:
  desc: null
  value:
    cli_version: 0.10.12
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.1
class_weight:
  desc: null
  value: balanced
criterion:
  desc: null
  value: entropy
max_depth:
  desc: null
  value: 10
max_features:
  desc: null
  value: 1
min_samples_leaf:
  desc: null
  value: 676
min_samples_split:
  desc: null
  value: 413
splitter:
  desc: null
  value: best
