wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: entropy
max_depth:
  value: 3
max_features:
  value: 10
min_samples_leaf:
  value: 605
min_samples_split:
  value: 469
splitter:
  value: best
