wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 10
max_features:
  value: 15
min_samples_leaf:
  value: 995
min_samples_split:
  value: 416
splitter:
  value: random
