wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 4
max_features:
  value: 30
min_samples_leaf:
  value: 386
min_samples_split:
  value: 178
splitter:
  value: best
