wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 8
max_features:
  value: 1
min_samples_leaf:
  value: 830
min_samples_split:
  value: 63
splitter:
  value: random
