wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 10
max_features:
  value: 17
min_samples_leaf:
  value: 668
min_samples_split:
  value: 699
splitter:
  value: random
