wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 8
max_features:
  value: 2
min_samples_leaf:
  value: 882
min_samples_split:
  value: 412
splitter:
  value: best
