wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 5
max_features:
  value: 27
min_samples_leaf:
  value: 497
min_samples_split:
  value: 936
splitter:
  value: best
