wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 6
max_features:
  value: 25
min_samples_leaf:
  value: 470
min_samples_split:
  value: 904
splitter:
  value: best
