wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: entropy
max_depth:
  value: 3
max_features:
  value: 35
min_samples_leaf:
  value: 719
min_samples_split:
  value: 115
splitter:
  value: best
