wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: entropy
max_depth:
  value: 5
max_features:
  value: 4
min_samples_leaf:
  value: 170
min_samples_split:
  value: 292
splitter:
  value: best
