wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: entropy
max_depth:
  value: 7
max_features:
  value: 35
min_samples_leaf:
  value: 896
min_samples_split:
  value: 280
splitter:
  value: random
