wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 5
max_features:
  value: 3
min_samples_leaf:
  value: 317
min_samples_split:
  value: 793
splitter:
  value: best
