wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: entropy
max_depth:
  value: 6
max_features:
  value: 19
min_samples_leaf:
  value: 205
min_samples_split:
  value: 871
splitter:
  value: random
