wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: entropy
max_depth:
  value: 9
max_features:
  value: 40
min_samples_leaf:
  value: 116
min_samples_split:
  value: 800
splitter:
  value: best
