wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: entropy
max_depth:
  value: 4
max_features:
  value: 12
min_samples_leaf:
  value: 397
min_samples_split:
  value: 72
splitter:
  value: random
