wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 7
max_features:
  value: 3
min_samples_leaf:
  value: 943
min_samples_split:
  value: 245
splitter:
  value: random
