wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: entropy
max_depth:
  value: 9
max_features:
  value: 17
min_samples_leaf:
  value: 536
min_samples_split:
  value: 593
splitter:
  value: random
