wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: entropy
max_depth:
  value: 9
max_features:
  value: 2
min_samples_leaf:
  value: 552
min_samples_split:
  value: 514
splitter:
  value: random
