wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: entropy
max_depth:
  value: 8
max_features:
  value: 40
min_samples_leaf:
  value: 330
min_samples_split:
  value: 481
splitter:
  value: random
