wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 9
max_features:
  value: 9
min_samples_leaf:
  value: 112
min_samples_split:
  value: 472
splitter:
  value: best
