wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: entropy
max_depth:
  value: 3
max_features:
  value: 33
min_samples_leaf:
  value: 108
min_samples_split:
  value: 147
splitter:
  value: random
