wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: entropy
max_depth:
  value: 9
max_features:
  value: 1
min_samples_leaf:
  value: 756
min_samples_split:
  value: 358
splitter:
  value: random
