wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: entropy
max_depth:
  value: 6
max_features:
  value: 25
min_samples_leaf:
  value: 729
min_samples_split:
  value: 725
splitter:
  value: best
