wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 9
max_features:
  value: 39
min_samples_leaf:
  value: 476
min_samples_split:
  value: 783
splitter:
  value: random
