wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 7
max_features:
  value: 33
min_samples_leaf:
  value: 141
min_samples_split:
  value: 232
splitter:
  value: best
