wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 9
max_features:
  value: 19
min_samples_leaf:
  value: 96
min_samples_split:
  value: 920
splitter:
  value: random
