wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 5
max_features:
  value: 8
min_samples_leaf:
  value: 134
min_samples_split:
  value: 632
splitter:
  value: best
