wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 9
max_features:
  value: 2
min_samples_leaf:
  value: 960
min_samples_split:
  value: 674
splitter:
  value: best
