wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: entropy
max_depth:
  value: 9
max_features:
  value: 16
min_samples_leaf:
  value: 183
min_samples_split:
  value: 754
splitter:
  value: random
