wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 3
max_features:
  value: 8
min_samples_leaf:
  value: 441
min_samples_split:
  value: 60
splitter:
  value: best
