wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: entropy
max_depth:
  value: 8
max_features:
  value: 26
min_samples_leaf:
  value: 752
min_samples_split:
  value: 667
splitter:
  value: random
