wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 3
max_features:
  value: 23
min_samples_leaf:
  value: 186
min_samples_split:
  value: 958
splitter:
  value: best
