wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 9
max_features:
  value: 11
min_samples_leaf:
  value: 67
min_samples_split:
  value: 778
splitter:
  value: best
