wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 4
max_features:
  value: 1
min_samples_leaf:
  value: 983
min_samples_split:
  value: 481
splitter:
  value: random
