wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: entropy
max_depth:
  value: 3
max_features:
  value: 5
min_samples_leaf:
  value: 417
min_samples_split:
  value: 126
splitter:
  value: random
