wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 10
max_features:
  value: 28
min_samples_leaf:
  value: 208
min_samples_split:
  value: 587
splitter:
  value: best
