wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: entropy
max_depth:
  value: 3
max_features:
  value: 3
min_samples_leaf:
  value: 321
min_samples_split:
  value: 136
splitter:
  value: best
