wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: entropy
max_depth:
  value: 5
max_features:
  value: 36
min_samples_leaf:
  value: 355
min_samples_split:
  value: 416
splitter:
  value: best
