wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 3
max_features:
  value: 29
min_samples_leaf:
  value: 270
min_samples_split:
  value: 526
splitter:
  value: random
