wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 3
max_features:
  value: 27
min_samples_leaf:
  value: 529
min_samples_split:
  value: 797
splitter:
  value: best
