wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: entropy
max_depth:
  value: 4
max_features:
  value: 6
min_samples_leaf:
  value: 409
min_samples_split:
  value: 609
splitter:
  value: random
