wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 7
max_features:
  value: 5
min_samples_leaf:
  value: 645
min_samples_split:
  value: 26
splitter:
  value: random
