wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 6
max_features:
  value: 35
min_samples_leaf:
  value: 281
min_samples_split:
  value: 938
splitter:
  value: random
