wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 7
max_features:
  value: 28
min_samples_leaf:
  value: 726
min_samples_split:
  value: 982
splitter:
  value: best
