wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 3
max_features:
  value: 22
min_samples_leaf:
  value: 75
min_samples_split:
  value: 994
splitter:
  value: best
