wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: entropy
max_depth:
  value: 8
max_features:
  value: 11
min_samples_leaf:
  value: 200
min_samples_split:
  value: 746
splitter:
  value: random
