wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: entropy
max_depth:
  value: 7
max_features:
  value: 40
min_samples_leaf:
  value: 172
min_samples_split:
  value: 339
splitter:
  value: random
