wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: entropy
max_depth:
  value: 5
max_features:
  value: 37
min_samples_leaf:
  value: 462
min_samples_split:
  value: 128
splitter:
  value: best
