wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 8
max_features:
  value: 36
min_samples_leaf:
  value: 914
min_samples_split:
  value: 107
splitter:
  value: random
