wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: entropy
max_depth:
  value: 8
max_features:
  value: 21
min_samples_leaf:
  value: 377
min_samples_split:
  value: 869
splitter:
  value: random
