wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: entropy
max_depth:
  value: 6
max_features:
  value: 7
min_samples_leaf:
  value: 458
min_samples_split:
  value: 760
splitter:
  value: random
