wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: entropy
max_depth:
  value: 5
max_features:
  value: 7
min_samples_leaf:
  value: 312
min_samples_split:
  value: 849
splitter:
  value: random
