wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: entropy
max_depth:
  value: 8
max_features:
  value: 14
min_samples_leaf:
  value: 102
min_samples_split:
  value: 752
splitter:
  value: random
