wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 6
max_features:
  value: 33
min_samples_leaf:
  value: 219
min_samples_split:
  value: 680
splitter:
  value: random
