wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: entropy
max_depth:
  value: 7
max_features:
  value: 15
min_samples_leaf:
  value: 300
min_samples_split:
  value: 720
splitter:
  value: random
