wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: entropy
max_depth:
  value: 4
max_features:
  value: 9
min_samples_leaf:
  value: 269
min_samples_split:
  value: 745
splitter:
  value: random
