wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: entropy
max_depth:
  value: 8
max_features:
  value: 6
min_samples_leaf:
  value: 386
min_samples_split:
  value: 144
splitter:
  value: best
