wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: entropy
max_depth:
  value: 8
max_features:
  value: 31
min_samples_leaf:
  value: 961
min_samples_split:
  value: 828
splitter:
  value: random
