wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: entropy
max_depth:
  value: 9
max_features:
  value: 31
min_samples_leaf:
  value: 369
min_samples_split:
  value: 521
splitter:
  value: best
