wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 4
max_features:
  value: 33
min_samples_leaf:
  value: 623
min_samples_split:
  value: 553
splitter:
  value: best
