wandb_version: 1

_callback:
  desc: null
  value: wandb.sdk.wandb_run.Run._config_callback
_items:
  desc: null
  value:
    _callback: wandb.sdk.wandb_run.Run._config_callback
    _items:
      _callback: wandb.sdk.wandb_run.Run._config_callback
      _items:
        _callback: wandb.sdk.wandb_run.Run._config_callback
        _items:
          _callback: wandb.sdk.wandb_run.Run._config_callback
          _items:
            _callback: wandb.sdk.wandb_run.Run._config_callback
            _items:
              _callback: wandb.sdk.wandb_run.Run._config_callback
              _items:
                _callback: wandb.sdk.wandb_run.Run._config_callback
                _items:
                  _callback: wandb.sdk.wandb_run.Run._config_callback
                  _items:
                    _callback: wandb.sdk.wandb_run.Run._config_callback
                    _items:
                      _wandb:
                        cli_version: 0.10.12
                        framework: sklearn
                        is_jupyter_run: false
                        is_kaggle_kernel: false
                        python_version: 3.9.1
                      class_weight: balanced
                      criterion: entropy
                      max_depth: 5
                      max_features: 21
                      min_samples_leaf: 235
                      min_samples_split: 348
                      splitter: best
                    _locked: {}
                    _settings: <wandb.sdk.wandb_settings.Settings object at 0x000001949EF0C430>
                    _users: {}
                    _users_cnt: 0
                    _users_inv: {}
                    _wandb:
                      cli_version: 0.10.12
                      framework: sklearn
                      is_jupyter_run: false
                      is_kaggle_kernel: false
                      python_version: 3.9.1
                    class_weight: balanced
                    criterion: gini
                    max_depth: 6
                    max_features: 33
                    min_samples_leaf: 219
                    min_samples_split: 680
                    splitter: random
                  _locked: {}
                  _settings: <wandb.sdk.wandb_settings.Settings object at 0x000001949F00AFA0>
                  _users: {}
                  _users_cnt: 0
                  _users_inv: {}
                  _wandb:
                    cli_version: 0.10.12
                    framework: sklearn
                    is_jupyter_run: false
                    is_kaggle_kernel: false
                    python_version: 3.9.1
                  class_weight: balanced
                  criterion: entropy
                  max_depth: 7
                  max_features: 15
                  min_samples_leaf: 300
                  min_samples_split: 720
                  splitter: random
                _locked: {}
                _settings: <wandb.sdk.wandb_settings.Settings object at 0x000001949F0153D0>
                _users: {}
                _users_cnt: 0
                _users_inv: {}
                _wandb:
                  cli_version: 0.10.12
                  framework: sklearn
                  is_jupyter_run: false
                  is_kaggle_kernel: false
                  python_version: 3.9.1
                class_weight: balanced
                criterion: entropy
                max_depth: 7
                max_features: 12
                min_samples_leaf: 421
                min_samples_split: 696
                splitter: random
              _locked: {}
              _settings: <wandb.sdk.wandb_settings.Settings object at 0x000001949F053F70>
              _users: {}
              _users_cnt: 0
              _users_inv: {}
              _wandb:
                cli_version: 0.10.12
                framework: sklearn
                is_jupyter_run: false
                is_kaggle_kernel: false
                python_version: 3.9.1
              class_weight: balanced
              criterion: entropy
              max_depth: 8
              max_features: 14
              min_samples_leaf: 102
              min_samples_split: 752
              splitter: random
            _locked: {}
            _settings: <wandb.sdk.wandb_settings.Settings object at 0x000001949F07FC70>
            _users: {}
            _users_cnt: 0
            _users_inv: {}
            _wandb:
              cli_version: 0.10.12
              framework: sklearn
              is_jupyter_run: false
              is_kaggle_kernel: false
              python_version: 3.9.1
            class_weight: balanced
            criterion: entropy
            max_depth: 8
            max_features: 21
            min_samples_leaf: 377
            min_samples_split: 869
            splitter: random
          _locked: {}
          _settings: <wandb.sdk.wandb_settings.Settings object at 0x000001949F01CCA0>
          _users: {}
          _users_cnt: 0
          _users_inv: {}
          _wandb:
            cli_version: 0.10.12
            framework: sklearn
            is_jupyter_run: false
            is_kaggle_kernel: false
            python_version: 3.9.1
          class_weight: balanced
          criterion: entropy
          max_depth: 5
          max_features: 7
          min_samples_leaf: 312
          min_samples_split: 849
          splitter: random
        _locked: {}
        _settings: <wandb.sdk.wandb_settings.Settings object at 0x000001949F819610>
        _users: {}
        _users_cnt: 0
        _users_inv: {}
        _wandb:
          cli_version: 0.10.12
          framework: sklearn
          is_jupyter_run: false
          is_kaggle_kernel: false
          python_version: 3.9.1
        class_weight: balanced
        criterion: entropy
        max_depth: 6
        max_features: 7
        min_samples_leaf: 458
        min_samples_split: 760
        splitter: random
      _locked: {}
      _settings: <wandb.sdk.wandb_settings.Settings object at 0x000001949F814C40>
      _users: {}
      _users_cnt: 0
      _users_inv: {}
      _wandb:
        cli_version: 0.10.12
        framework: sklearn
        is_jupyter_run: false
        is_kaggle_kernel: false
        python_version: 3.9.1
      class_weight: balanced
      criterion: entropy
      max_depth: 4
      max_features: 9
      min_samples_leaf: 269
      min_samples_split: 745
      splitter: random
    _locked: {}
    _settings: <wandb.sdk.wandb_settings.Settings object at 0x000001949F845100>
    _users: {}
    _users_cnt: 0
    _users_inv: {}
    _wandb:
      cli_version: 0.10.12
      framework: sklearn
      is_jupyter_run: false
      is_kaggle_kernel: false
      python_version: 3.9.1
    class_weight: balanced
    criterion: entropy
    max_depth: 7
    max_features: 6
    min_samples_leaf: 541
    min_samples_split: 837
    splitter: random
_locked:
  desc: null
  value: {}
_settings:
  desc: null
  value: <wandb.sdk.wandb_settings.Settings object at 0x000001949F849A60>
_users:
  desc: null
  value: {}
_users_cnt:
  desc: null
  value: 0
_users_inv:
  desc: null
  value: {}
_wandb:
  desc: null
  value:
    cli_version: 0.10.12
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.1
class_weight:
  desc: null
  value: balanced
criterion:
  desc: null
  value: entropy
max_depth:
  desc: null
  value: 5
max_features:
  desc: null
  value: 16
min_samples_leaf:
  desc: null
  value: 590
min_samples_split:
  desc: null
  value: 652
splitter:
  desc: null
  value: random
