wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 8
max_features:
  value: 35
min_samples_leaf:
  value: 788
min_samples_split:
  value: 272
splitter:
  value: random
