wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: entropy
max_depth:
  value: 7
max_features:
  value: 32
min_samples_leaf:
  value: 58
min_samples_split:
  value: 731
splitter:
  value: random
