wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 7
max_features:
  value: 2
min_samples_leaf:
  value: 568
min_samples_split:
  value: 103
splitter:
  value: best
