wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: entropy
max_depth:
  value: 6
max_features:
  value: 21
min_samples_leaf:
  value: 744
min_samples_split:
  value: 870
splitter:
  value: best
