wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: entropy
max_depth:
  value: 9
max_features:
  value: 21
min_samples_leaf:
  value: 162
min_samples_split:
  value: 75
splitter:
  value: random
