wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: entropy
max_depth:
  value: 9
max_features:
  value: 27
min_samples_leaf:
  value: 390
min_samples_split:
  value: 739
splitter:
  value: random
