wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 5
max_features:
  value: 36
min_samples_leaf:
  value: 845
min_samples_split:
  value: 433
splitter:
  value: random
