wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 8
max_features:
  value: 32
min_samples_leaf:
  value: 305
min_samples_split:
  value: 914
splitter:
  value: random
