wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: entropy
max_depth:
  value: 7
max_features:
  value: 37
min_samples_leaf:
  value: 94
min_samples_split:
  value: 971
splitter:
  value: best
