wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: entropy
max_depth:
  value: 6
max_features:
  value: 14
min_samples_leaf:
  value: 260
min_samples_split:
  value: 42
splitter:
  value: best
