wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 10
max_features:
  value: 2
min_samples_leaf:
  value: 528
min_samples_split:
  value: 687
splitter:
  value: best
