wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: entropy
max_depth:
  value: 3
max_features:
  value: 2
min_samples_leaf:
  value: 896
min_samples_split:
  value: 635
splitter:
  value: random
