wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 10
max_features:
  value: 4
min_samples_leaf:
  value: 179
min_samples_split:
  value: 588
splitter:
  value: best
