wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: entropy
max_depth:
  value: 6
max_features:
  value: 40
min_samples_leaf:
  value: 644
min_samples_split:
  value: 396
splitter:
  value: best
