wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: entropy
max_depth:
  value: 4
max_features:
  value: 37
min_samples_leaf:
  value: 163
min_samples_split:
  value: 346
splitter:
  value: random
