wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 9
max_features:
  value: 40
min_samples_leaf:
  value: 806
min_samples_split:
  value: 818
splitter:
  value: random
