wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 5
max_features:
  value: 6
min_samples_leaf:
  value: 197
min_samples_split:
  value: 903
splitter:
  value: random
