wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 4
max_features:
  value: 4
min_samples_leaf:
  value: 267
min_samples_split:
  value: 656
splitter:
  value: random
