wandb_version: 1

_callback:
  desc: null
  value: wandb.sdk.wandb_run.Run._config_callback
_items:
  desc: null
  value:
    _callback: wandb.sdk.wandb_run.Run._config_callback
    _items:
      _callback: wandb.sdk.wandb_run.Run._config_callback
      _items:
        _callback: wandb.sdk.wandb_run.Run._config_callback
        _items:
          _callback: wandb.sdk.wandb_run.Run._config_callback
          _items:
            _callback: wandb.sdk.wandb_run.Run._config_callback
            _items:
              _callback: wandb.sdk.wandb_run.Run._config_callback
              _items:
                _callback: wandb.sdk.wandb_run.Run._config_callback
                _items:
                  _callback: wandb.sdk.wandb_run.Run._config_callback
                  _items:
                    _callback: wandb.sdk.wandb_run.Run._config_callback
                    _items:
                      _callback: wandb.sdk.wandb_run.Run._config_callback
                      _items:
                        _callback: wandb.sdk.wandb_run.Run._config_callback
                        _items:
                          _callback: wandb.sdk.wandb_run.Run._config_callback
                          _items:
                            _wandb:
                              cli_version: 0.10.12
                              framework: sklearn
                              is_jupyter_run: false
                              is_kaggle_kernel: false
                              python_version: 3.9.1
                            class_weight: balanced
                            criterion: gini
                            max_depth: 6
                            max_features: 31
                            min_samples_leaf: 336
                            min_samples_split: 249
                            splitter: random
                          _locked: {}
                          _settings: <wandb.sdk.wandb_settings.Settings object at
                            0x00000200FBF4C400>
                          _users: {}
                          _users_cnt: 0
                          _users_inv: {}
                          _wandb:
                            cli_version: 0.10.12
                            framework: sklearn
                            is_jupyter_run: false
                            is_kaggle_kernel: false
                            python_version: 3.9.1
                          class_weight: balanced
                          criterion: gini
                          max_depth: 3
                          max_features: 19
                          min_samples_leaf: 874
                          min_samples_split: 561
                          splitter: random
                        _locked: {}
                        _settings: <wandb.sdk.wandb_settings.Settings object at 0x00000200FC0542E0>
                        _users: {}
                        _users_cnt: 0
                        _users_inv: {}
                        _wandb:
                          cli_version: 0.10.12
                          framework: sklearn
                          is_jupyter_run: false
                          is_kaggle_kernel: false
                          python_version: 3.9.1
                        class_weight: balanced
                        criterion: entropy
                        max_depth: 8
                        max_features: 18
                        min_samples_leaf: 934
                        min_samples_split: 596
                        splitter: random
                      _locked: {}
                      _settings: <wandb.sdk.wandb_settings.Settings object at 0x00000200FC05AFA0>
                      _users: {}
                      _users_cnt: 0
                      _users_inv: {}
                      _wandb:
                        cli_version: 0.10.12
                        framework: sklearn
                        is_jupyter_run: false
                        is_kaggle_kernel: false
                        python_version: 3.9.1
                      class_weight: balanced
                      criterion: gini
                      max_depth: 7
                      max_features: 4
                      min_samples_leaf: 383
                      min_samples_split: 613
                      splitter: random
                    _locked: {}
                    _settings: <wandb.sdk.wandb_settings.Settings object at 0x00000200FC0B0790>
                    _users: {}
                    _users_cnt: 0
                    _users_inv: {}
                    _wandb:
                      cli_version: 0.10.12
                      framework: sklearn
                      is_jupyter_run: false
                      is_kaggle_kernel: false
                      python_version: 3.9.1
                    class_weight: balanced
                    criterion: entropy
                    max_depth: 7
                    max_features: 5
                    min_samples_leaf: 885
                    min_samples_split: 633
                    splitter: best
                  _locked: {}
                  _settings: <wandb.sdk.wandb_settings.Settings object at 0x00000200FC0BEEE0>
                  _users: {}
                  _users_cnt: 0
                  _users_inv: {}
                  _wandb:
                    cli_version: 0.10.12
                    framework: sklearn
                    is_jupyter_run: false
                    is_kaggle_kernel: false
                    python_version: 3.9.1
                  class_weight: balanced
                  criterion: entropy
                  max_depth: 10
                  max_features: 4
                  min_samples_leaf: 763
                  min_samples_split: 778
                  splitter: random
                _locked: {}
                _settings: <wandb.sdk.wandb_settings.Settings object at 0x00000200FC09FD00>
                _users: {}
                _users_cnt: 0
                _users_inv: {}
                _wandb:
                  cli_version: 0.10.12
                  framework: sklearn
                  is_jupyter_run: false
                  is_kaggle_kernel: false
                  python_version: 3.9.1
                class_weight: balanced
                criterion: entropy
                max_depth: 9
                max_features: 26
                min_samples_leaf: 848
                min_samples_split: 310
                splitter: random
              _locked: {}
              _settings: <wandb.sdk.wandb_settings.Settings object at 0x00000200FD912940>
              _users: {}
              _users_cnt: 0
              _users_inv: {}
              _wandb:
                cli_version: 0.10.12
                framework: sklearn
                is_jupyter_run: false
                is_kaggle_kernel: false
                python_version: 3.9.1
              class_weight: balanced
              criterion: gini
              max_depth: 7
              max_features: 21
              min_samples_leaf: 74
              min_samples_split: 176
              splitter: random
            _locked: {}
            _settings: <wandb.sdk.wandb_settings.Settings object at 0x00000200FD9344C0>
            _users: {}
            _users_cnt: 0
            _users_inv: {}
            _wandb:
              cli_version: 0.10.12
              framework: sklearn
              is_jupyter_run: false
              is_kaggle_kernel: false
              python_version: 3.9.1
            class_weight: balanced
            criterion: entropy
            max_depth: 9
            max_features: 28
            min_samples_leaf: 470
            min_samples_split: 131
            splitter: random
          _locked: {}
          _settings: <wandb.sdk.wandb_settings.Settings object at 0x00000200FD946B20>
          _users: {}
          _users_cnt: 0
          _users_inv: {}
          _wandb:
            cli_version: 0.10.12
            framework: sklearn
            is_jupyter_run: false
            is_kaggle_kernel: false
            python_version: 3.9.1
          class_weight: balanced
          criterion: gini
          max_depth: 10
          max_features: 13
          min_samples_leaf: 642
          min_samples_split: 282
          splitter: random
        _locked: {}
        _settings: <wandb.sdk.wandb_settings.Settings object at 0x00000200FCFDDE80>
        _users: {}
        _users_cnt: 0
        _users_inv: {}
        _wandb:
          cli_version: 0.10.12
          framework: sklearn
          is_jupyter_run: false
          is_kaggle_kernel: false
          python_version: 3.9.1
        class_weight: balanced
        criterion: gini
        max_depth: 3
        max_features: 37
        min_samples_leaf: 884
        min_samples_split: 396
        splitter: best
      _locked: {}
      _settings: <wandb.sdk.wandb_settings.Settings object at 0x00000200FCFF34C0>
      _users: {}
      _users_cnt: 0
      _users_inv: {}
      _wandb:
        cli_version: 0.10.12
        framework: sklearn
        is_jupyter_run: false
        is_kaggle_kernel: false
        python_version: 3.9.1
      class_weight: balanced
      criterion: gini
      max_depth: 9
      max_features: 4
      min_samples_leaf: 245
      min_samples_split: 852
      splitter: best
    _locked: {}
    _settings: <wandb.sdk.wandb_settings.Settings object at 0x00000200FCFF7CA0>
    _users: {}
    _users_cnt: 0
    _users_inv: {}
    _wandb:
      cli_version: 0.10.12
      framework: sklearn
      is_jupyter_run: false
      is_kaggle_kernel: false
      python_version: 3.9.1
    class_weight: balanced
    criterion: gini
    max_depth: 10
    max_features: 18
    min_samples_leaf: 810
    min_samples_split: 351
    splitter: best
_locked:
  desc: null
  value: {}
_settings:
  desc: null
  value: <wandb.sdk.wandb_settings.Settings object at 0x00000200FC0E2760>
_users:
  desc: null
  value: {}
_users_cnt:
  desc: null
  value: 0
_users_inv:
  desc: null
  value: {}
_wandb:
  desc: null
  value:
    cli_version: 0.10.12
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.1
class_weight:
  desc: null
  value: balanced
criterion:
  desc: null
  value: entropy
max_depth:
  desc: null
  value: 7
max_features:
  desc: null
  value: 37
min_samples_leaf:
  desc: null
  value: 342
min_samples_split:
  desc: null
  value: 308
splitter:
  desc: null
  value: best
