wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 8
max_features:
  value: 29
min_samples_leaf:
  value: 713
min_samples_split:
  value: 7
splitter:
  value: best
