wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: entropy
max_depth:
  value: 3
max_features:
  value: 4
min_samples_leaf:
  value: 977
min_samples_split:
  value: 300
splitter:
  value: best
