wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: entropy
max_depth:
  value: 9
max_features:
  value: 36
min_samples_leaf:
  value: 457
min_samples_split:
  value: 3
splitter:
  value: best
