wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: entropy
max_depth:
  value: 8
max_features:
  value: 8
min_samples_leaf:
  value: 665
min_samples_split:
  value: 877
splitter:
  value: best
