wandb_version: 1

_callback:
  desc: null
  value: wandb.sdk.wandb_run.Run._config_callback
_items:
  desc: null
  value:
    _wandb:
      cli_version: 0.10.12
      framework: sklearn
      is_jupyter_run: false
      is_kaggle_kernel: false
      python_version: 3.9.1
    class_weight: balanced
    criterion: entropy
    max_depth: 4
    max_features: 32
    min_samples_leaf: 738
    min_samples_split: 544
    splitter: best
_locked:
  desc: null
  value: {}
_settings:
  desc: null
  value: <wandb.sdk.wandb_settings.Settings object at 0x00000234CC7ABA00>
_users:
  desc: null
  value: {}
_users_cnt:
  desc: null
  value: 0
_users_inv:
  desc: null
  value: {}
_wandb:
  desc: null
  value:
    cli_version: 0.10.12
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.1
class_weight:
  desc: null
  value: balanced
criterion:
  desc: null
  value: entropy
max_depth:
  desc: null
  value: 9
max_features:
  desc: null
  value: 25
min_samples_leaf:
  desc: null
  value: 78
min_samples_split:
  desc: null
  value: 318
splitter:
  desc: null
  value: random
