wandb_version: 1

_callback:
  desc: null
  value: wandb.sdk.wandb_run.Run._config_callback
_items:
  desc: null
  value:
    _callback: wandb.sdk.wandb_run.Run._config_callback
    _items:
      _wandb:
        cli_version: 0.10.12
        framework: sklearn
        is_jupyter_run: false
        is_kaggle_kernel: false
        python_version: 3.9.1
      class_weight: balanced
      criterion: gini
      max_depth: 10
      max_features: 8
      min_samples_leaf: 414
      min_samples_split: 728
      splitter: random
    _locked: {}
    _settings: <wandb.sdk.wandb_settings.Settings object at 0x00000203FFB1C400>
    _users: {}
    _users_cnt: 0
    _users_inv: {}
    _wandb:
      cli_version: 0.10.12
      framework: sklearn
      is_jupyter_run: false
      is_kaggle_kernel: false
      python_version: 3.9.1
    class_weight: balanced
    criterion: entropy
    max_depth: 3
    max_features: 13
    min_samples_leaf: 806
    min_samples_split: 371
    splitter: random
_locked:
  desc: null
  value: {}
_settings:
  desc: null
  value: <wandb.sdk.wandb_settings.Settings object at 0x00000203FFC2ADC0>
_users:
  desc: null
  value: {}
_users_cnt:
  desc: null
  value: 0
_users_inv:
  desc: null
  value: {}
_wandb:
  desc: null
  value:
    cli_version: 0.10.12
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.1
class_weight:
  desc: null
  value: balanced
criterion:
  desc: null
  value: gini
max_depth:
  desc: null
  value: 3
max_features:
  desc: null
  value: 30
min_samples_leaf:
  desc: null
  value: 936
min_samples_split:
  desc: null
  value: 166
splitter:
  desc: null
  value: best
