wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: entropy
max_depth:
  value: 4
max_features:
  value: 30
min_samples_leaf:
  value: 248
min_samples_split:
  value: 32
splitter:
  value: random
