wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 3
max_features:
  value: 4
min_samples_leaf:
  value: 914
min_samples_split:
  value: 716
splitter:
  value: best
