wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 10
max_features:
  value: 36
min_samples_leaf:
  value: 147
min_samples_split:
  value: 534
splitter:
  value: random
