wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 10
max_features:
  value: 38
min_samples_leaf:
  value: 79
min_samples_split:
  value: 364
splitter:
  value: random
