wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: entropy
max_depth:
  value: 3
max_features:
  value: 22
min_samples_leaf:
  value: 642
min_samples_split:
  value: 54
splitter:
  value: best
