wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 6
max_features:
  value: 20
min_samples_leaf:
  value: 857
min_samples_split:
  value: 784
splitter:
  value: random
