wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 4
max_features:
  value: 38
min_samples_leaf:
  value: 564
min_samples_split:
  value: 307
splitter:
  value: best
