wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: entropy
max_depth:
  value: 3
max_features:
  value: 8
min_samples_leaf:
  value: 975
min_samples_split:
  value: 856
splitter:
  value: best
