wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: entropy
max_depth:
  value: 6
max_features:
  value: 5
min_samples_leaf:
  value: 318
min_samples_split:
  value: 650
splitter:
  value: random
