wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 6
max_features:
  value: 35
min_samples_leaf:
  value: 278
min_samples_split:
  value: 355
splitter:
  value: random
