wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: entropy
max_depth:
  value: 3
max_features:
  value: 31
min_samples_leaf:
  value: 132
min_samples_split:
  value: 981
splitter:
  value: best
