wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 6
max_features:
  value: 31
min_samples_leaf:
  value: 618
min_samples_split:
  value: 179
splitter:
  value: random
