wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: entropy
max_depth:
  value: 9
max_features:
  value: 10
min_samples_leaf:
  value: 112
min_samples_split:
  value: 716
splitter:
  value: best
