wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: entropy
max_depth:
  value: 10
max_features:
  value: 38
min_samples_leaf:
  value: 901
min_samples_split:
  value: 200
splitter:
  value: random
