wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: entropy
max_depth:
  value: 5
max_features:
  value: 11
min_samples_leaf:
  value: 723
min_samples_split:
  value: 120
splitter:
  value: random
