wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 3
max_features:
  value: 30
min_samples_leaf:
  value: 936
min_samples_split:
  value: 166
splitter:
  value: best
