wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 10
max_features:
  value: 8
min_samples_leaf:
  value: 414
min_samples_split:
  value: 728
splitter:
  value: random
