wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 6
max_features:
  value: 30
min_samples_leaf:
  value: 601
min_samples_split:
  value: 427
splitter:
  value: random
