wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: entropy
max_depth:
  value: 9
max_features:
  value: 34
min_samples_leaf:
  value: 786
min_samples_split:
  value: 821
splitter:
  value: random
