wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 6
max_features:
  value: 5
min_samples_leaf:
  value: 443
min_samples_split:
  value: 505
splitter:
  value: best
