wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 4
max_features:
  value: 7
min_samples_leaf:
  value: 227
min_samples_split:
  value: 418
splitter:
  value: best
