wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 10
max_features:
  value: 11
min_samples_leaf:
  value: 920
min_samples_split:
  value: 212
splitter:
  value: best
