wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 7
max_features:
  value: 26
min_samples_leaf:
  value: 999
min_samples_split:
  value: 160
splitter:
  value: random
