wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 8
max_features:
  value: 37
min_samples_leaf:
  value: 126
min_samples_split:
  value: 636
splitter:
  value: random
