wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 7
max_features:
  value: 38
min_samples_leaf:
  value: 465
min_samples_split:
  value: 673
splitter:
  value: random
