wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: entropy
max_depth:
  value: 9
max_features:
  value: 25
min_samples_leaf:
  value: 359
min_samples_split:
  value: 848
splitter:
  value: best
