wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 7
max_features:
  value: 37
min_samples_leaf:
  value: 400
min_samples_split:
  value: 175
splitter:
  value: random
