wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 3
max_features:
  value: 25
min_samples_leaf:
  value: 126
min_samples_split:
  value: 696
splitter:
  value: best
