wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 6
max_features:
  value: 38
min_samples_leaf:
  value: 487
min_samples_split:
  value: 675
splitter:
  value: best
