wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: entropy
max_depth:
  value: 6
max_features:
  value: 12
min_samples_leaf:
  value: 769
min_samples_split:
  value: 943
splitter:
  value: random
