wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: entropy
max_depth:
  value: 8
max_features:
  value: 36
min_samples_leaf:
  value: 187
min_samples_split:
  value: 463
splitter:
  value: random
