wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 3
max_features:
  value: 23
min_samples_leaf:
  value: 116
min_samples_split:
  value: 62
splitter:
  value: best
