wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 3
max_features:
  value: 40
min_samples_leaf:
  value: 777
min_samples_split:
  value: 348
splitter:
  value: best
