wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 8
max_features:
  value: 2
min_samples_leaf:
  value: 902
min_samples_split:
  value: 892
splitter:
  value: random
