wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 7
max_features:
  value: 24
min_samples_leaf:
  value: 602
min_samples_split:
  value: 994
splitter:
  value: best
