wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: entropy
max_depth:
  value: 5
max_features:
  value: 10
min_samples_leaf:
  value: 378
min_samples_split:
  value: 595
splitter:
  value: random
