wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 8
max_features:
  value: 6
min_samples_leaf:
  value: 826
min_samples_split:
  value: 505
splitter:
  value: best
