wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: entropy
max_depth:
  value: 4
max_features:
  value: 23
min_samples_leaf:
  value: 441
min_samples_split:
  value: 894
splitter:
  value: random
