wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 4
max_features:
  value: 10
min_samples_leaf:
  value: 545
min_samples_split:
  value: 589
splitter:
  value: best
