wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 8
max_features:
  value: 8
min_samples_leaf:
  value: 996
min_samples_split:
  value: 918
splitter:
  value: best
