wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 4
max_features:
  value: 8
min_samples_leaf:
  value: 990
min_samples_split:
  value: 382
splitter:
  value: random
