wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 8
max_features:
  value: 23
min_samples_leaf:
  value: 345
min_samples_split:
  value: 833
splitter:
  value: random
