wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: entropy
max_depth:
  value: 9
max_features:
  value: 4
min_samples_leaf:
  value: 578
min_samples_split:
  value: 683
splitter:
  value: random
