wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 9
max_features:
  value: 38
min_samples_leaf:
  value: 304
min_samples_split:
  value: 161
splitter:
  value: random
