wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 3
max_features:
  value: 20
min_samples_leaf:
  value: 576
min_samples_split:
  value: 586
splitter:
  value: best
