wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 8
max_features:
  value: 40
min_samples_leaf:
  value: 981
min_samples_split:
  value: 591
splitter:
  value: best
