wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: entropy
max_depth:
  value: 3
max_features:
  value: 11
min_samples_leaf:
  value: 868
min_samples_split:
  value: 570
splitter:
  value: best
