wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 7
max_features:
  value: 10
min_samples_leaf:
  value: 110
min_samples_split:
  value: 954
splitter:
  value: random
