wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 3
max_features:
  value: 16
min_samples_leaf:
  value: 725
min_samples_split:
  value: 56
splitter:
  value: best
