wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 8
max_features:
  value: 40
min_samples_leaf:
  value: 350
min_samples_split:
  value: 289
splitter:
  value: best
