wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 7
max_features:
  value: 31
min_samples_leaf:
  value: 811
min_samples_split:
  value: 67
splitter:
  value: best
