wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: entropy
max_depth:
  value: 8
max_features:
  value: 5
min_samples_leaf:
  value: 146
min_samples_split:
  value: 318
splitter:
  value: best
