wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: entropy
max_depth:
  value: 6
max_features:
  value: 40
min_samples_leaf:
  value: 27
min_samples_split:
  value: 719
splitter:
  value: best
