wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 8
max_features:
  value: 20
min_samples_leaf:
  value: 536
min_samples_split:
  value: 72
splitter:
  value: best
