wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 7
max_features:
  value: 25
min_samples_leaf:
  value: 467
min_samples_split:
  value: 919
splitter:
  value: best
