wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: entropy
max_depth:
  value: 7
max_features:
  value: 11
min_samples_leaf:
  value: 785
min_samples_split:
  value: 585
splitter:
  value: best
