wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: entropy
max_depth:
  value: 6
max_features:
  value: 37
min_samples_leaf:
  value: 598
min_samples_split:
  value: 602
splitter:
  value: best
