wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: entropy
max_depth:
  value: 8
max_features:
  value: 2
min_samples_leaf:
  value: 290
min_samples_split:
  value: 19
splitter:
  value: random
