wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: entropy
max_depth:
  value: 3
max_features:
  value: 39
min_samples_leaf:
  value: 628
min_samples_split:
  value: 654
splitter:
  value: best
