wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: entropy
max_depth:
  value: 4
max_features:
  value: 1
min_samples_leaf:
  value: 862
min_samples_split:
  value: 152
splitter:
  value: random
