wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 10
max_features:
  value: 20
min_samples_leaf:
  value: 418
min_samples_split:
  value: 890
splitter:
  value: best
