wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: entropy
max_depth:
  value: 3
max_features:
  value: 32
min_samples_leaf:
  value: 593
min_samples_split:
  value: 805
splitter:
  value: best
