wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 4
max_features:
  value: 30
min_samples_leaf:
  value: 629
min_samples_split:
  value: 536
splitter:
  value: best
