wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: entropy
max_depth:
  value: 8
max_features:
  value: 29
min_samples_leaf:
  value: 607
min_samples_split:
  value: 937
splitter:
  value: best
