wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 7
max_features:
  value: 9
min_samples_leaf:
  value: 517
min_samples_split:
  value: 61
splitter:
  value: random
