wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 6
max_features:
  value: 13
min_samples_leaf:
  value: 437
min_samples_split:
  value: 247
splitter:
  value: random
