wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: entropy
max_depth:
  value: 3
max_features:
  value: 26
min_samples_leaf:
  value: 587
min_samples_split:
  value: 121
splitter:
  value: random
