wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: entropy
max_depth:
  value: 9
max_features:
  value: 8
min_samples_leaf:
  value: 435
min_samples_split:
  value: 78
splitter:
  value: random
