wandb_version: 1

_callback:
  desc: null
  value: wandb.sdk.wandb_run.Run._config_callback
_items:
  desc: null
  value:
    _callback: wandb.sdk.wandb_run.Run._config_callback
    _items:
      _callback: wandb.sdk.wandb_run.Run._config_callback
      _items:
        _callback: wandb.sdk.wandb_run.Run._config_callback
        _items:
          _callback: wandb.sdk.wandb_run.Run._config_callback
          _items:
            _callback: wandb.sdk.wandb_run.Run._config_callback
            _items:
              _callback: wandb.sdk.wandb_run.Run._config_callback
              _items:
                _callback: wandb.sdk.wandb_run.Run._config_callback
                _items:
                  _callback: wandb.sdk.wandb_run.Run._config_callback
                  _items:
                    _callback: wandb.sdk.wandb_run.Run._config_callback
                    _items:
                      _wandb:
                        cli_version: 0.10.12
                        framework: sklearn
                        is_jupyter_run: false
                        is_kaggle_kernel: false
                        python_version: 3.9.1
                      class_weight: balanced
                      criterion: entropy
                      max_depth: 8
                      max_features: 33
                      min_samples_leaf: 12
                      min_samples_split: 80
                      splitter: best
                    _locked: {}
                    _settings: <wandb.sdk.wandb_settings.Settings object at 0x0000012DBEAFC400>
                    _users: {}
                    _users_cnt: 0
                    _users_inv: {}
                    _wandb:
                      cli_version: 0.10.12
                      framework: sklearn
                      is_jupyter_run: false
                      is_kaggle_kernel: false
                      python_version: 3.9.1
                    class_weight: balanced
                    criterion: entropy
                    max_depth: 6
                    max_features: 26
                    min_samples_leaf: 5
                    min_samples_split: 313
                    splitter: random
                  _locked: {}
                  _settings: <wandb.sdk.wandb_settings.Settings object at 0x0000012DBEAF3880>
                  _users: {}
                  _users_cnt: 0
                  _users_inv: {}
                  _wandb:
                    cli_version: 0.10.12
                    framework: sklearn
                    is_jupyter_run: false
                    is_kaggle_kernel: false
                    python_version: 3.9.1
                  class_weight: balanced
                  criterion: entropy
                  max_depth: 9
                  max_features: 21
                  min_samples_leaf: 218
                  min_samples_split: 435
                  splitter: best
                _locked: {}
                _settings: <wandb.sdk.wandb_settings.Settings object at 0x0000012DBEC44F40>
                _users: {}
                _users_cnt: 0
                _users_inv: {}
                _wandb:
                  cli_version: 0.10.12
                  framework: sklearn
                  is_jupyter_run: false
                  is_kaggle_kernel: false
                  python_version: 3.9.1
                class_weight: balanced
                criterion: entropy
                max_depth: 9
                max_features: 34
                min_samples_leaf: 74
                min_samples_split: 117
                splitter: random
              _locked: {}
              _settings: <wandb.sdk.wandb_settings.Settings object at 0x0000012DBEC44250>
              _users: {}
              _users_cnt: 0
              _users_inv: {}
              _wandb:
                cli_version: 0.10.12
                framework: sklearn
                is_jupyter_run: false
                is_kaggle_kernel: false
                python_version: 3.9.1
              class_weight: balanced
              criterion: entropy
              max_depth: 8
              max_features: 32
              min_samples_leaf: 969
              min_samples_split: 530
              splitter: random
            _locked: {}
            _settings: <wandb.sdk.wandb_settings.Settings object at 0x0000012DBEC78490>
            _users: {}
            _users_cnt: 0
            _users_inv: {}
            _wandb:
              cli_version: 0.10.12
              framework: sklearn
              is_jupyter_run: false
              is_kaggle_kernel: false
              python_version: 3.9.1
            class_weight: balanced
            criterion: entropy
            max_depth: 4
            max_features: 31
            min_samples_leaf: 933
            min_samples_split: 76
            splitter: random
          _locked: {}
          _settings: <wandb.sdk.wandb_settings.Settings object at 0x0000012DBEC042E0>
          _users: {}
          _users_cnt: 0
          _users_inv: {}
          _wandb:
            cli_version: 0.10.12
            framework: sklearn
            is_jupyter_run: false
            is_kaggle_kernel: false
            python_version: 3.9.1
          class_weight: balanced
          criterion: entropy
          max_depth: 10
          max_features: 12
          min_samples_leaf: 603
          min_samples_split: 552
          splitter: random
        _locked: {}
        _settings: <wandb.sdk.wandb_settings.Settings object at 0x0000012DBEC64970>
        _users: {}
        _users_cnt: 0
        _users_inv: {}
        _wandb:
          cli_version: 0.10.12
          framework: sklearn
          is_jupyter_run: false
          is_kaggle_kernel: false
          python_version: 3.9.1
        class_weight: balanced
        criterion: entropy
        max_depth: 7
        max_features: 39
        min_samples_leaf: 111
        min_samples_split: 490
        splitter: best
      _locked: {}
      _settings: <wandb.sdk.wandb_settings.Settings object at 0x0000012DBFB9DAC0>
      _users: {}
      _users_cnt: 0
      _users_inv: {}
      _wandb:
        cli_version: 0.10.12
        framework: sklearn
        is_jupyter_run: false
        is_kaggle_kernel: false
        python_version: 3.9.1
      class_weight: balanced
      criterion: gini
      max_depth: 9
      max_features: 24
      min_samples_leaf: 484
      min_samples_split: 831
      splitter: random
    _locked: {}
    _settings: <wandb.sdk.wandb_settings.Settings object at 0x0000012DBFBAC790>
    _users: {}
    _users_cnt: 0
    _users_inv: {}
    _wandb:
      cli_version: 0.10.12
      framework: sklearn
      is_jupyter_run: false
      is_kaggle_kernel: false
      python_version: 3.9.1
    class_weight: balanced
    criterion: gini
    max_depth: 4
    max_features: 20
    min_samples_leaf: 523
    min_samples_split: 420
    splitter: random
_locked:
  desc: null
  value: {}
_settings:
  desc: null
  value: <wandb.sdk.wandb_settings.Settings object at 0x0000012DBFBB7D60>
_users:
  desc: null
  value: {}
_users_cnt:
  desc: null
  value: 0
_users_inv:
  desc: null
  value: {}
_wandb:
  desc: null
  value:
    cli_version: 0.10.12
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.1
class_weight:
  desc: null
  value: balanced
criterion:
  desc: null
  value: gini
max_depth:
  desc: null
  value: 10
max_features:
  desc: null
  value: 16
min_samples_leaf:
  desc: null
  value: 981
min_samples_split:
  desc: null
  value: 165
splitter:
  desc: null
  value: random
