wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: entropy
max_depth:
  value: 8
max_features:
  value: 18
min_samples_leaf:
  value: 934
min_samples_split:
  value: 596
splitter:
  value: random
