wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: entropy
max_depth:
  value: 9
max_features:
  value: 28
min_samples_leaf:
  value: 470
min_samples_split:
  value: 131
splitter:
  value: random
