wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 7
max_features:
  value: 4
min_samples_leaf:
  value: 383
min_samples_split:
  value: 613
splitter:
  value: random
