wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 9
max_features:
  value: 4
min_samples_leaf:
  value: 245
min_samples_split:
  value: 852
splitter:
  value: best
