wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 3
max_features:
  value: 37
min_samples_leaf:
  value: 884
min_samples_split:
  value: 396
splitter:
  value: best
