wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 3
max_features:
  value: 19
min_samples_leaf:
  value: 874
min_samples_split:
  value: 561
splitter:
  value: random
