wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: entropy
max_depth:
  value: 7
max_features:
  value: 5
min_samples_leaf:
  value: 885
min_samples_split:
  value: 633
splitter:
  value: best
