wandb_version: 1

_callback:
  desc: null
  value: wandb.sdk.wandb_run.Run._config_callback
_items:
  desc: null
  value:
    _callback: wandb.sdk.wandb_run.Run._config_callback
    _items:
      _callback: wandb.sdk.wandb_run.Run._config_callback
      _items:
        _callback: wandb.sdk.wandb_run.Run._config_callback
        _items:
          _callback: wandb.sdk.wandb_run.Run._config_callback
          _items:
            _callback: wandb.sdk.wandb_run.Run._config_callback
            _items:
              _callback: wandb.sdk.wandb_run.Run._config_callback
              _items:
                _callback: wandb.sdk.wandb_run.Run._config_callback
                _items:
                  _callback: wandb.sdk.wandb_run.Run._config_callback
                  _items:
                    _callback: wandb.sdk.wandb_run.Run._config_callback
                    _items:
                      _callback: wandb.sdk.wandb_run.Run._config_callback
                      _items:
                        _callback: wandb.sdk.wandb_run.Run._config_callback
                        _items:
                          _callback: wandb.sdk.wandb_run.Run._config_callback
                          _items:
                            _wandb:
                              cli_version: 0.10.12
                              framework: sklearn
                              is_jupyter_run: false
                              is_kaggle_kernel: false
                              python_version: 3.9.1
                            class_weight: balanced
                            criterion: entropy
                            max_depth: 8
                            max_features: 28
                            min_samples_leaf: 398
                            min_samples_split: 928
                            splitter: random
                          _locked: {}
                          _settings: <wandb.sdk.wandb_settings.Settings object at
                            0x000002985D81F220>
                          _users: {}
                          _users_cnt: 0
                          _users_inv: {}
                          _wandb:
                            cli_version: 0.10.12
                            framework: sklearn
                            is_jupyter_run: false
                            is_kaggle_kernel: false
                            python_version: 3.9.1
                          class_weight: balanced
                          criterion: gini
                          max_depth: 9
                          max_features: 34
                          min_samples_leaf: 579
                          min_samples_split: 953
                          splitter: best
                        _locked: {}
                        _settings: <wandb.sdk.wandb_settings.Settings object at 0x000002985D6E01F0>
                        _users: {}
                        _users_cnt: 0
                        _users_inv: {}
                        _wandb:
                          cli_version: 0.10.12
                          framework: sklearn
                          is_jupyter_run: false
                          is_kaggle_kernel: false
                          python_version: 3.9.1
                        class_weight: balanced
                        criterion: entropy
                        max_depth: 7
                        max_features: 39
                        min_samples_leaf: 78
                        min_samples_split: 368
                        splitter: best
                      _locked: {}
                      _settings: <wandb.sdk.wandb_settings.Settings object at 0x000002985D896970>
                      _users: {}
                      _users_cnt: 0
                      _users_inv: {}
                      _wandb:
                        cli_version: 0.10.12
                        framework: sklearn
                        is_jupyter_run: false
                        is_kaggle_kernel: false
                        python_version: 3.9.1
                      class_weight: balanced
                      criterion: gini
                      max_depth: 10
                      max_features: 33
                      min_samples_leaf: 385
                      min_samples_split: 945
                      splitter: random
                    _locked: {}
                    _settings: <wandb.sdk.wandb_settings.Settings object at 0x000002985D877C10>
                    _users: {}
                    _users_cnt: 0
                    _users_inv: {}
                    _wandb:
                      cli_version: 0.10.12
                      framework: sklearn
                      is_jupyter_run: false
                      is_kaggle_kernel: false
                      python_version: 3.9.1
                    class_weight: balanced
                    criterion: gini
                    max_depth: 9
                    max_features: 38
                    min_samples_leaf: 448
                    min_samples_split: 919
                    splitter: best
                  _locked: {}
                  _settings: <wandb.sdk.wandb_settings.Settings object at 0x000002985D8B1E80>
                  _users: {}
                  _users_cnt: 0
                  _users_inv: {}
                  _wandb:
                    cli_version: 0.10.12
                    framework: sklearn
                    is_jupyter_run: false
                    is_kaggle_kernel: false
                    python_version: 3.9.1
                  class_weight: balanced
                  criterion: gini
                  max_depth: 8
                  max_features: 24
                  min_samples_leaf: 938
                  min_samples_split: 979
                  splitter: random
                _locked: {}
                _settings: <wandb.sdk.wandb_settings.Settings object at 0x000002985D8C5F70>
                _users: {}
                _users_cnt: 0
                _users_inv: {}
                _wandb:
                  cli_version: 0.10.12
                  framework: sklearn
                  is_jupyter_run: false
                  is_kaggle_kernel: false
                  python_version: 3.9.1
                class_weight: balanced
                criterion: gini
                max_depth: 9
                max_features: 30
                min_samples_leaf: 739
                min_samples_split: 732
                splitter: best
              _locked: {}
              _settings: <wandb.sdk.wandb_settings.Settings object at 0x000002985D8CCF70>
              _users: {}
              _users_cnt: 0
              _users_inv: {}
              _wandb:
                cli_version: 0.10.12
                framework: sklearn
                is_jupyter_run: false
                is_kaggle_kernel: false
                python_version: 3.9.1
              class_weight: balanced
              criterion: entropy
              max_depth: 10
              max_features: 28
              min_samples_leaf: 918
              min_samples_split: 776
              splitter: best
            _locked: {}
            _settings: <wandb.sdk.wandb_settings.Settings object at 0x000002985D8E5040>
            _users: {}
            _users_cnt: 0
            _users_inv: {}
            _wandb:
              cli_version: 0.10.12
              framework: sklearn
              is_jupyter_run: false
              is_kaggle_kernel: false
              python_version: 3.9.1
            class_weight: balanced
            criterion: entropy
            max_depth: 9
            max_features: 22
            min_samples_leaf: 955
            min_samples_split: 666
            splitter: best
          _locked: {}
          _settings: <wandb.sdk.wandb_settings.Settings object at 0x000002985D905FD0>
          _users: {}
          _users_cnt: 0
          _users_inv: {}
          _wandb:
            cli_version: 0.10.12
            framework: sklearn
            is_jupyter_run: false
            is_kaggle_kernel: false
            python_version: 3.9.1
          class_weight: balanced
          criterion: gini
          max_depth: 9
          max_features: 26
          min_samples_leaf: 984
          min_samples_split: 587
          splitter: best
        _locked: {}
        _settings: <wandb.sdk.wandb_settings.Settings object at 0x000002985D8FADF0>
        _users: {}
        _users_cnt: 0
        _users_inv: {}
        _wandb:
          cli_version: 0.10.12
          framework: sklearn
          is_jupyter_run: false
          is_kaggle_kernel: false
          python_version: 3.9.1
        class_weight: balanced
        criterion: gini
        max_depth: 9
        max_features: 24
        min_samples_leaf: 937
        min_samples_split: 541
        splitter: best
      _locked: {}
      _settings: <wandb.sdk.wandb_settings.Settings object at 0x000002985D8B2790>
      _users: {}
      _users_cnt: 0
      _users_inv: {}
      _wandb:
        cli_version: 0.10.12
        framework: sklearn
        is_jupyter_run: false
        is_kaggle_kernel: false
        python_version: 3.9.1
      class_weight: balanced
      criterion: entropy
      max_depth: 10
      max_features: 28
      min_samples_leaf: 905
      min_samples_split: 748
      splitter: best
    _locked: {}
    _settings: <wandb.sdk.wandb_settings.Settings object at 0x000002985D913EB0>
    _users: {}
    _users_cnt: 0
    _users_inv: {}
    _wandb:
      cli_version: 0.10.12
      framework: sklearn
      is_jupyter_run: false
      is_kaggle_kernel: false
      python_version: 3.9.1
    class_weight: balanced
    criterion: gini
    max_depth: 5
    max_features: 8
    min_samples_leaf: 20
    min_samples_split: 481
    splitter: best
_locked:
  desc: null
  value: {}
_settings:
  desc: null
  value: <wandb.sdk.wandb_settings.Settings object at 0x000002985DB70AC0>
_users:
  desc: null
  value: {}
_users_cnt:
  desc: null
  value: 0
_users_inv:
  desc: null
  value: {}
_wandb:
  desc: null
  value:
    cli_version: 0.10.12
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.1
class_weight:
  desc: null
  value: balanced
criterion:
  desc: null
  value: entropy
max_depth:
  desc: null
  value: 6
max_features:
  desc: null
  value: 13
min_samples_leaf:
  desc: null
  value: 52
min_samples_split:
  desc: null
  value: 478
splitter:
  desc: null
  value: best
