wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: entropy
max_depth:
  value: 10
max_features:
  value: 36
min_samples_leaf:
  value: 603
min_samples_split:
  value: 555
splitter:
  value: random
