wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 7
max_features:
  value: 12
min_samples_leaf:
  value: 695
min_samples_split:
  value: 785
splitter:
  value: best
