wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: entropy
max_depth:
  value: 6
max_features:
  value: 28
min_samples_leaf:
  value: 734
min_samples_split:
  value: 218
splitter:
  value: best
