wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 6
max_features:
  value: 26
min_samples_leaf:
  value: 637
min_samples_split:
  value: 810
splitter:
  value: random
