wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 5
max_features:
  value: 1
min_samples_leaf:
  value: 769
min_samples_split:
  value: 423
splitter:
  value: best
