wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: entropy
max_depth:
  value: 4
max_features:
  value: 40
min_samples_leaf:
  value: 508
min_samples_split:
  value: 388
splitter:
  value: random
