wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 3
max_features:
  value: 24
min_samples_leaf:
  value: 491
min_samples_split:
  value: 109
splitter:
  value: best
