wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: entropy
max_depth:
  value: 7
max_features:
  value: 19
min_samples_leaf:
  value: 436
min_samples_split:
  value: 49
splitter:
  value: best
