wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 8
max_features:
  value: 13
min_samples_leaf:
  value: 614
min_samples_split:
  value: 957
splitter:
  value: random
