wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 10
max_features:
  value: 32
min_samples_leaf:
  value: 579
min_samples_split:
  value: 315
splitter:
  value: best
