wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 6
max_features:
  value: 4
min_samples_leaf:
  value: 118
min_samples_split:
  value: 674
splitter:
  value: best
