wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 10
max_features:
  value: 5
min_samples_leaf:
  value: 600
min_samples_split:
  value: 601
splitter:
  value: random
