wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 8
max_features:
  value: 14
min_samples_leaf:
  value: 420
min_samples_split:
  value: 478
splitter:
  value: best
