wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 10
max_features:
  value: 30
min_samples_leaf:
  value: 450
min_samples_split:
  value: 318
splitter:
  value: best
