wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 6
max_features:
  value: 10
min_samples_leaf:
  value: 929
min_samples_split:
  value: 645
splitter:
  value: best
