wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: entropy
max_depth:
  value: 6
max_features:
  value: 30
min_samples_leaf:
  value: 667
min_samples_split:
  value: 597
splitter:
  value: random
