wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: entropy
max_depth:
  value: 5
max_features:
  value: 35
min_samples_leaf:
  value: 120
min_samples_split:
  value: 195
splitter:
  value: random
