wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 6
max_features:
  value: 22
min_samples_leaf:
  value: 909
min_samples_split:
  value: 257
splitter:
  value: best
