wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 4
max_features:
  value: 5
min_samples_leaf:
  value: 830
min_samples_split:
  value: 915
splitter:
  value: best
