wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 3
max_features:
  value: 31
min_samples_leaf:
  value: 203
min_samples_split:
  value: 962
splitter:
  value: random
