wandb_version: 1

class_weight:
  value: balanced
criterion:
  value: gini
max_depth:
  value: 8
max_features:
  value: 14
min_samples_leaf:
  value: 561
min_samples_split:
  value: 708
splitter:
  value: random
